/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frames;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class _2_Login extends javax.swing.JFrame {

    /**
     * Creates new form _2_Login_Create
     */
    public _2_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        Skip = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        OrLabel = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        signin = new javax.swing.JButton();
        Usern = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login Page");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmailLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email ID :");
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        PassLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        PassLabel.setForeground(new java.awt.Color(255, 255, 255));
        PassLabel.setText("Password :");
        getContentPane().add(PassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        Skip.setFont(new java.awt.Font("Sylfaen", 2, 18)); // NOI18N
        Skip.setForeground(new java.awt.Color(204, 204, 204));
        Skip.setText("Skip Sign in >>");
        Skip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SkipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SkipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SkipMouseExited(evt);
            }
        });
        getContentPane().add(Skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 110, 30));

        Email.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Email.setForeground(new java.awt.Color(102, 102, 102));
        Email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Email.setToolTipText("Enter Email ID");
        Email.setAlignmentX(1.0F);
        Email.setAlignmentY(1.0F);
        Email.setPreferredSize(new java.awt.Dimension(6, 30));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 300, 40));

        Pass.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        Pass.setForeground(new java.awt.Color(102, 102, 102));
        Pass.setToolTipText("Enter Password");
        Pass.setEchoChar('\u2022');
        Pass.setPreferredSize(new java.awt.Dimension(6, 30));
        getContentPane().add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 300, 40));

        OrLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        OrLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrLabel.setText("OR");
        getContentPane().add(OrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        create.setBackground(new java.awt.Color(74, 168, 246));
        create.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("CREATE ACCOUNT");
        create.setBorder(null);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.setPreferredSize(new java.awt.Dimension(230, 30));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 270, 40));

        signin.setBackground(new java.awt.Color(74, 168, 246));
        signin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("SIGN IN");
        signin.setBorder(null);
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin.setPreferredSize(new java.awt.Dimension(110, 30));
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 40));

        Usern.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Usern.setForeground(new java.awt.Color(102, 102, 102));
        Usern.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Usern.setToolTipText("Enter Email ID");
        Usern.setAlignmentX(1.0F);
        Usern.setAlignmentY(1.0F);
        Usern.setPreferredSize(new java.awt.Dimension(6, 30));
        getContentPane().add(Usern, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 300, 40));

        UserLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("Username :");
        getContentPane().add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        LoginLabel.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        LoginLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOODIEZZ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Kristen ITC", 0, 36), new java.awt.Color(18, 148, 242))); // NOI18N
        getContentPane().add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 350, 460));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/Sign in.jpg"))); // NOI18N
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
String Emailid = Email.getText(), Pwd = new String (Pass.getPassword()), Uname = Usern.getText();

if(Emailid.isEmpty() || Pwd.isEmpty() || Uname.isEmpty()){
    JOptionPane.showMessageDialog(this, "<html><font size = 15 face = rockwell color = Green>Fill All The Fields", null, 2);}
else{
    try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
        Statement stat = c.createStatement();
    
        String query = "Select * from login where Username = '"+ Uname +"';";
        ResultSet rs = stat.executeQuery(query);
        while (rs.next()){
            String ei = rs.getString("Email_id");
            String pas = rs.getString("Password");
            String un = rs.getString("Username");        

            if(Emailid.equals(ei) && Pwd.equals(pas)){
                int Ans = JOptionPane.showConfirmDialog(this, "<html><font color = green face = Rockwell size = 7>Succesfully Logged in<br>Go Ahead?", null, 0, 1);
                if(Ans == JOptionPane.YES_OPTION){
                    _3_Location.main(null);
                    this.dispose();
            }break;
            } 
            else{
                if(!Emailid.equals(ei) && Pwd.equals(pas))
                    JOptionPane.showConfirmDialog(this, "<html><font color = red>Incorrect Email ID", null, -1, 0);
                if(!Pwd.equals(pas) && Emailid.equals(ei))
                    JOptionPane.showConfirmDialog(this, "<html><font color = red>Incorrect Password", null, -1, 0);
                if(!Emailid.equals(ei) && !Pwd.equals(pas))
                    JOptionPane.showConfirmDialog(this, "<html><font color = red>Incorrect Email ID and Password", null, -1, 0);
            }
        }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error in Signing in", null, 2);
    } 
}
        // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void SkipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SkipMouseClicked
this.dispose();
_3_Location.main(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_SkipMouseClicked

    private void SkipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SkipMouseEntered
Skip.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_SkipMouseEntered

    private void SkipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SkipMouseExited
Skip.setForeground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_SkipMouseExited

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
_2_Create_Account.main(null);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new _2_Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel OrLabel;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel Skip;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField Usern;
    private javax.swing.JButton create;
    private javax.swing.JButton signin;
    // End of variables declaration//GEN-END:variables
}
