/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frames;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Recaptcha extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Recaptcha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        C1 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        C2 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        C3 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        C4 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        C5 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        C6 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        C9 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        C8 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        C7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 51, 102));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirmation of Robot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 28), new java.awt.Color(0, 131, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 115, 0));
        jLabel2.setText("Select Images having Carrots");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, -1));

        jCheckBox1.setBorder(null);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102538.jpg"))); // NOI18N
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 100));

        jCheckBox2.setBorder(null);
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102747.jpg"))); // NOI18N
        jPanel1.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 100));

        jCheckBox3.setBorder(null);
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102828.jpg"))); // NOI18N
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 100, 100));

        jCheckBox4.setBorder(null);
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102814.jpg"))); // NOI18N
        jPanel1.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 100));

        jCheckBox5.setBorder(null);
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102620.jpg"))); // NOI18N
        jPanel1.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, 100));

        jCheckBox6.setBorder(null);
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102636.jpg"))); // NOI18N
        jPanel1.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 100));

        jCheckBox7.setBorder(null);
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        C9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102801.jpg"))); // NOI18N
        jPanel1.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, 100));

        jCheckBox8.setBorder(null);
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102700.jpg"))); // NOI18N
        jPanel1.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 100, 100));

        jCheckBox9.setBorder(null);
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recaptcha_Images/IMG_20190506_102724.jpg"))); // NOI18N
        jPanel1.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 100));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Verify");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jCheckBox1.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected() && jCheckBox8.isSelected() && !jCheckBox2.isSelected() && !jCheckBox3.isSelected() && !jCheckBox4.isSelected() && !jCheckBox7.isSelected() && !jCheckBox9.isSelected()){
    JOptionPane.showMessageDialog(this, "<html><font size = 15 face = rockwell color = blue>Verified");
    this.dispose();
    _2_Create_Account.ConRobo.setSelected(true);
}        
else{
    JOptionPane.showConfirmDialog(this, "<html><font color=red >Error Robot not Verified", "Error", -1, 0);
    this.dispose();
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recaptcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recaptcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recaptcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recaptcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recaptcha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel C9;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
