/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurants;

import Project_Frames._2_Login;
import Project_Frames._3_Location;
import Project_Frames._4_Main_Order_Gujarat_Ahemdabad;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Ahemdabad_Makhan_Bhog extends javax.swing.JFrame {
Connection con;
ResultSet rs;
Statement stat;
    /**
     * Creates new form Gangour
     */
    public Ahemdabad_Makhan_Bhog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CartBtn = new javax.swing.JButton();
        PALabel = new javax.swing.JLabel();
        RestaurantLabel = new javax.swing.JLabel();
        LocationLabel = new javax.swing.JLabel();
        SigninLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        LabelBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Main_panel = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        S1 = new javax.swing.JSeparator();
        S2 = new javax.swing.JSeparator();
        S3 = new javax.swing.JSeparator();
        S4 = new javax.swing.JSeparator();
        SweetPanel = new javax.swing.JPanel();
        Add1 = new javax.swing.JButton();
        C1 = new javax.swing.JSpinner();
        I1 = new javax.swing.JLabel();
        IS1 = new javax.swing.JSeparator();
        Add2 = new javax.swing.JButton();
        C2 = new javax.swing.JSpinner();
        I2 = new javax.swing.JLabel();
        IS2 = new javax.swing.JSeparator();
        Add3 = new javax.swing.JButton();
        C3 = new javax.swing.JSpinner();
        I3 = new javax.swing.JLabel();
        IS3 = new javax.swing.JSeparator();
        Add4 = new javax.swing.JButton();
        C4 = new javax.swing.JSpinner();
        I4 = new javax.swing.JLabel();
        IS4 = new javax.swing.JSeparator();
        Add5 = new javax.swing.JButton();
        C5 = new javax.swing.JSpinner();
        I5 = new javax.swing.JLabel();
        IS5 = new javax.swing.JSeparator();
        Add6 = new javax.swing.JButton();
        C6 = new javax.swing.JSpinner();
        I6 = new javax.swing.JLabel();
        IS6 = new javax.swing.JSeparator();
        Add7 = new javax.swing.JButton();
        C7 = new javax.swing.JSpinner();
        I7 = new javax.swing.JLabel();
        IS7 = new javax.swing.JSeparator();
        Add8 = new javax.swing.JButton();
        C8 = new javax.swing.JSpinner();
        I8 = new javax.swing.JLabel();
        IS8 = new javax.swing.JSeparator();
        Add9 = new javax.swing.JButton();
        C9 = new javax.swing.JSpinner();
        I9 = new javax.swing.JLabel();
        IS9 = new javax.swing.JSeparator();
        Add10 = new javax.swing.JButton();
        C10 = new javax.swing.JSpinner();
        I10 = new javax.swing.JLabel();
        IS10 = new javax.swing.JSeparator();
        Add11 = new javax.swing.JButton();
        C11 = new javax.swing.JSpinner();
        I11 = new javax.swing.JLabel();
        IS11 = new javax.swing.JSeparator();
        Add12 = new javax.swing.JButton();
        C12 = new javax.swing.JSpinner();
        I12 = new javax.swing.JLabel();
        IS12 = new javax.swing.JSeparator();
        Add13 = new javax.swing.JButton();
        C13 = new javax.swing.JSpinner();
        I13 = new javax.swing.JLabel();
        IS13 = new javax.swing.JSeparator();
        Add14 = new javax.swing.JButton();
        C14 = new javax.swing.JSpinner();
        I14 = new javax.swing.JLabel();
        IS14 = new javax.swing.JSeparator();
        Add15 = new javax.swing.JButton();
        C15 = new javax.swing.JSpinner();
        I15 = new javax.swing.JLabel();
        IS15 = new javax.swing.JSeparator();
        KB_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Makhan Bhog");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartBtn.setBackground(new java.awt.Color(0, 153, 204));
        CartBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        CartBtn.setText("Cart");
        CartBtn.setRequestFocusEnabled(false);
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 140, -1));

        PALabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        PALabel.setForeground(new java.awt.Color(51, 51, 51));
        PALabel.setText("Makhan Bhog");
        jPanel1.add(PALabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        RestaurantLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        RestaurantLabel.setForeground(new java.awt.Color(142, 142, 142));
        RestaurantLabel.setText("Restaurant(Ahemdabad) /");
        RestaurantLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestaurantLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseExited(evt);
            }
        });
        jPanel1.add(RestaurantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 40));

        LocationLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        LocationLabel.setForeground(new java.awt.Color(142, 142, 142));
        LocationLabel.setText("Location /");
        LocationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LocationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LocationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LocationLabelMouseExited(evt);
            }
        });
        jPanel1.add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 40));

        SigninLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        SigninLabel.setForeground(new java.awt.Color(142, 142, 142));
        SigninLabel.setText("Sign in /");
        SigninLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SigninLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SigninLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SigninLabelMouseExited(evt);
            }
        });
        jPanel1.add(SigninLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, -1, 40));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Gujarat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/Foodiezz.png"))); // NOI18N
        jPanel1.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        Address.setFont(new java.awt.Font("Narkisim", 0, 24)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Papyrus", 0, 24))); // NOI18N
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 460, 80));

        LabelBack.setOpaque(true);
        jPanel1.add(LabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1350, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(153, 153, 153));
        TypeLabel.setText("Sweets");
        Main_panel.add(TypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        S1.setBackground(new java.awt.Color(102, 102, 102));
        S1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 10, 50));

        S2.setBackground(new java.awt.Color(102, 102, 102));
        S2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 10, 50));

        S3.setBackground(new java.awt.Color(102, 102, 102));
        S3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 10, 450));

        S4.setBackground(new java.awt.Color(102, 102, 102));
        Main_panel.add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 1050, 10));

        SweetPanel.setBackground(new java.awt.Color(255, 255, 255));
        SweetPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add1.setBackground(new java.awt.Color(9, 101, 0));
        Add1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("ADD");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        C1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        I1.setBackground(new java.awt.Color(255, 255, 255));
        I1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/6 Mohanthal-768x512 60.jpg"))); // NOI18N
        I1.setText("<html>Mohanthal<br><font color = gray >Sweets</font><br><br><b>Rs.60");
        I1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I1.setIconTextGap(15);
        I1.setRequestFocusEnabled(false);
        I1.setVerifyInputWhenFocusTarget(false);
        I1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 220));

        IS1.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1050, 10));

        Add2.setBackground(new java.awt.Color(9, 101, 0));
        Add2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("ADD");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 80, 30));

        C2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 80, 30));

        I2.setBackground(new java.awt.Color(255, 255, 255));
        I2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/7 Adadiya-768x561 60.jpg"))); // NOI18N
        I2.setText("<html>Adadiya<br><font color = gray >Sweets</font><br><br><b>Rs.60");
        I2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I2.setIconTextGap(15);
        I2.setRequestFocusEnabled(false);
        I2.setVerifyInputWhenFocusTarget(false);
        I2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1050, 220));

        IS2.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1050, 10));

        Add3.setBackground(new java.awt.Color(9, 101, 0));
        Add3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("ADD");
        Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add3ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 80, 30));

        C3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 80, 30));

        I3.setBackground(new java.awt.Color(255, 255, 255));
        I3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/8 Peda-768x512 70.jpg"))); // NOI18N
        I3.setText("<html>Peda<br><font color = gray >Sweets</font><br><br><b>Rs.70");
        I3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I3.setIconTextGap(15);
        I3.setRequestFocusEnabled(false);
        I3.setVerifyInputWhenFocusTarget(false);
        I3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1050, 220));

        IS3.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1050, 10));

        Add4.setBackground(new java.awt.Color(9, 101, 0));
        Add4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));
        Add4.setText("ADD");
        Add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add4ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 740, 80, 30));

        C4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 740, 80, 30));

        I4.setBackground(new java.awt.Color(255, 255, 255));
        I4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/9 Mesub-768x512 75.jpg"))); // NOI18N
        I4.setText("<html>Mesub<br><font color = gray >Sweets</font><br><br><b>Rs.75");
        I4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I4.setIconTextGap(15);
        I4.setRequestFocusEnabled(false);
        I4.setVerifyInputWhenFocusTarget(false);
        I4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1050, 220));

        IS4.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 1050, 10));

        Add5.setBackground(new java.awt.Color(9, 101, 0));
        Add5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));
        Add5.setText("ADD");
        Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add5ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 990, 80, 30));

        C5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 990, 80, 30));

        I5.setBackground(new java.awt.Color(255, 255, 255));
        I5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/10 kalakand 75.jpg"))); // NOI18N
        I5.setText("<html>Kalakand<br><font color = gray >Sweets</font><br><br><b>Rs.75");
        I5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I5.setIconTextGap(15);
        I5.setRequestFocusEnabled(false);
        I5.setVerifyInputWhenFocusTarget(false);
        I5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 970, 1050, 220));

        IS5.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1200, 1050, 10));

        Add6.setBackground(new java.awt.Color(9, 101, 0));
        Add6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));
        Add6.setText("ADD");
        Add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add6ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1240, 80, 30));

        C6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1240, 80, 30));

        I6.setBackground(new java.awt.Color(255, 255, 255));
        I6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/11 Keri-No-Ras-768x514 85.jpg"))); // NOI18N
        I6.setText("<html>Keri No Ras (Seasonal)<br><font color = gray >Sweets</font><br><br><b>Rs.85");
        I6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I6.setIconTextGap(15);
        I6.setRequestFocusEnabled(false);
        I6.setVerifyInputWhenFocusTarget(false);
        I6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1220, 1050, 220));

        IS6.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1450, 1050, 10));

        Add7.setBackground(new java.awt.Color(9, 101, 0));
        Add7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add7.setForeground(new java.awt.Color(255, 255, 255));
        Add7.setText("ADD");
        Add7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add7ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1490, 80, 30));

        C7.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1490, 80, 30));

        I7.setBackground(new java.awt.Color(255, 255, 255));
        I7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/12 Barfi 90.jpg"))); // NOI18N
        I7.setText("<html>Barfi<br><font color = gray >Sweets</font><br><br><b>Rs.90");
        I7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I7.setIconTextGap(15);
        I7.setRequestFocusEnabled(false);
        I7.setVerifyInputWhenFocusTarget(false);
        I7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1470, 1050, 220));

        IS7.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1700, 1050, 10));

        Add8.setBackground(new java.awt.Color(9, 101, 0));
        Add8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add8.setForeground(new java.awt.Color(255, 255, 255));
        Add8.setText("ADD");
        Add8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add8ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1730, 80, 30));

        C8.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1730, 80, 30));

        I8.setBackground(new java.awt.Color(255, 255, 255));
        I8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/14 Sutarfeni 100.jpg"))); // NOI18N
        I8.setText("<html>Sutarfeni<br><font color = gray >Sweets</font><br><br><b>Rs.100");
        I8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I8.setIconTextGap(15);
        I8.setRequestFocusEnabled(false);
        I8.setVerifyInputWhenFocusTarget(false);
        I8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1710, 1050, 220));

        IS8.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1940, 1050, 10));

        Add9.setBackground(new java.awt.Color(9, 101, 0));
        Add9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add9.setForeground(new java.awt.Color(255, 255, 255));
        Add9.setText("ADD");
        Add9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add9ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1980, 80, 30));

        C9.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1980, 80, 30));

        I9.setBackground(new java.awt.Color(255, 255, 255));
        I9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/15 Ghevar-1-768x43 115.jpg"))); // NOI18N
        I9.setText("<html>Ghevar<br><font color = gray >Sweets</font><br><br><b>Rs.115");
        I9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I9.setIconTextGap(15);
        I9.setRequestFocusEnabled(false);
        I9.setVerifyInputWhenFocusTarget(false);
        I9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1960, 1050, 220));

        IS9.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2190, 1050, 10));

        Add10.setBackground(new java.awt.Color(9, 101, 0));
        Add10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add10.setForeground(new java.awt.Color(255, 255, 255));
        Add10.setText("ADD");
        Add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add10ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2220, 80, 30));

        C10.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2220, 80, 30));

        I10.setBackground(new java.awt.Color(255, 255, 255));
        I10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/16 Malpua-1-768x576 120.jpg"))); // NOI18N
        I10.setText("<html>Malpua<br><font color = gray >Sweets</font><br><br><b>Rs.120");
        I10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I10.setIconTextGap(15);
        I10.setRequestFocusEnabled(false);
        I10.setVerifyInputWhenFocusTarget(false);
        I10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2200, 1050, 220));

        IS10.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2430, 1050, 10));

        Add11.setBackground(new java.awt.Color(9, 101, 0));
        Add11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add11.setForeground(new java.awt.Color(255, 255, 255));
        Add11.setText("ADD");
        Add11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add11ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2470, 80, 30));

        C11.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2470, 80, 30));

        I11.setBackground(new java.awt.Color(255, 255, 255));
        I11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/17 Halwasan-768x438 125.jpg"))); // NOI18N
        I11.setText("<html>Halwasan<br><font color = gray >Sweets</font><br><br><b>Rs.125");
        I11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I11.setIconTextGap(15);
        I11.setRequestFocusEnabled(false);
        I11.setVerifyInputWhenFocusTarget(false);
        I11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2450, 1050, 220));

        IS11.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2680, 1050, 10));

        Add12.setBackground(new java.awt.Color(9, 101, 0));
        Add12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add12.setForeground(new java.awt.Color(255, 255, 255));
        Add12.setText("ADD");
        Add12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add12ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2710, 80, 30));

        C12.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2710, 80, 30));

        I12.setBackground(new java.awt.Color(255, 255, 255));
        I12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/18 Basundi-1 125.jpg"))); // NOI18N
        I12.setText("<html>Basundi<br><font color = gray >Sweets</font><br><br><b>Rs.125");
        I12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I12.setIconTextGap(15);
        I12.setRequestFocusEnabled(false);
        I12.setVerifyInputWhenFocusTarget(false);
        I12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2690, 1050, 220));

        IS12.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2920, 1050, 10));

        Add13.setBackground(new java.awt.Color(9, 101, 0));
        Add13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add13.setForeground(new java.awt.Color(255, 255, 255));
        Add13.setText("ADD");
        Add13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add13ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2950, 80, 30));

        C13.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2950, 80, 30));

        I13.setBackground(new java.awt.Color(255, 255, 255));
        I13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/19 Kopra-Pak-768x512 130.jpg"))); // NOI18N
        I13.setText("<html>Kopra Pak<br><font color = gray >Sweets</font><br><br><b>Rs.130");
        I13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I13.setIconTextGap(15);
        I13.setRequestFocusEnabled(false);
        I13.setVerifyInputWhenFocusTarget(false);
        I13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2930, 1050, 220));

        IS13.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3160, 1050, 10));

        Add14.setBackground(new java.awt.Color(9, 101, 0));
        Add14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add14.setForeground(new java.awt.Color(255, 255, 255));
        Add14.setText("ADD");
        Add14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add14ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 3190, 80, 30));

        C14.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 3190, 80, 30));

        I14.setBackground(new java.awt.Color(255, 255, 255));
        I14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/20 rasmalai 140.jpg"))); // NOI18N
        I14.setText("<html>Rasmalai<br><font color = gray >Sweets</font><br><br><b>Rs.140");
        I14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I14.setIconTextGap(15);
        I14.setRequestFocusEnabled(false);
        I14.setVerifyInputWhenFocusTarget(false);
        I14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3170, 1050, 220));

        IS14.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3400, 1050, 10));

        Add15.setBackground(new java.awt.Color(9, 101, 0));
        Add15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add15.setForeground(new java.awt.Color(255, 255, 255));
        Add15.setText("ADD");
        Add15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add15ActionPerformed(evt);
            }
        });
        SweetPanel.add(Add15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 3440, 80, 30));

        C15.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SweetPanel.add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 3440, 80, 30));

        I15.setBackground(new java.awt.Color(255, 255, 255));
        I15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Makhan Bhog(Ahmd)/Sweets/21 Ghari 160.jpg"))); // NOI18N
        I15.setText("<html>Ghari<br><font color = gray >Sweets</font><br><br><b>Rs.160");
        I15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I15.setIconTextGap(15);
        I15.setRequestFocusEnabled(false);
        I15.setVerifyInputWhenFocusTarget(false);
        I15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SweetPanel.add(I15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3420, 1050, 220));

        IS15.setBackground(new java.awt.Color(224, 224, 224));
        SweetPanel.add(IS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3650, 1050, 10));

        Main_panel.add(SweetPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, 3650));

        KB_Label.setBackground(new java.awt.Color(0, 15, 40));
        KB_Label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        KB_Label.setForeground(new java.awt.Color(255, 255, 255));
        KB_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restaurants/Ahemdabad/Makhan Bhog.jpg"))); // NOI18N
        KB_Label.setText("<html><font color = 'white' size = 15>Makhan Bhog</font><br><t><font color = gray>Ahemdabad</br><br>Sweets</font></br><br><br><br>4.3 / 5 <t> <t> <t><t> <t> <t> <t> <t><t> <t><t><t><t><t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>   <font color = white><t>    Rs.110</font><t>  <t>  <t> <t> <t>  <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>    <t> <t>  <t>  <t>   <t>  <t>  <t>  <t>  <t> <font color = white>  15 Minutes </font><br><font size=5 color = gray> 550+ Ratings<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t> <t>  <t> <t> <t>Cost For Two<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>  <t>    Delivery Time</font></br>"); // NOI18N
        KB_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new java.awt.Color(0, 15, 40)));
        KB_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KB_Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        KB_Label.setIconTextGap(20);
        KB_Label.setOpaque(true);
        KB_Label.setRequestFocusEnabled(false);
        KB_Label.setVerifyInputWhenFocusTarget(false);
        KB_Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(KB_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 280));

        jScrollPane1.setViewportView(Main_panel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1350, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setLocationRelativeTo(null);
        try{
    Class.forName("java.sql.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
    Statement stat = con.createStatement();
    String query = "Select * from Location;";
    rs = stat.executeQuery(query);
    while(rs.next()){
        String pn = rs.getString("Plot_no");
        String ar = rs.getString("Area");
        String land = rs.getString("Landmark");
        String pin = rs.getString("Pincode");
        String ct = rs.getString("City");
        String resi = rs.getString("Residence");
        Address.setText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
        Address.setToolTipText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
                
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, "Error in Adress",null,-2);
}
        
C1.setVisible(false);
C2.setVisible(false);
C3.setVisible(false);
C4.setVisible(false);
C5.setVisible(false);
C6.setVisible(false);
C7.setVisible(false);
C8.setVisible(false);
C9.setVisible(false);
C10.setVisible(false);
C11.setVisible(false);
C12.setVisible(false);
C13.setVisible(false);
C14.setVisible(false);
C15.setVisible(false);

SweetPanel.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void RestaurantLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = blue>Go back to Restaurants(Ahemdabad) Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            Project_Frames._4_Main_Order_Gujarat_Ahemdabad.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseClicked

    private void RestaurantLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseEntered
        RestaurantLabel.setText("<html><u>Restaurant(Ahemdabad)</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseEntered

    private void RestaurantLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseExited
        RestaurantLabel.setText("Restaurant(Ahemdabad) /");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseExited

    private void LocationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = Green>Go back to Location Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _3_Location.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseClicked

    private void LocationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseEntered
        LocationLabel.setText("<html><u>Location</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseEntered

    private void LocationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseExited
        LocationLabel.setText("Location /");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseExited

    private void SigninLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = orange>Go back to Sign in Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _2_Login.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseClicked

    private void SigninLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseEntered
        SigninLabel.setText("<html><u>Sign in</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseEntered

    private void SigninLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseExited
        SigninLabel.setText("Sign in /");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseExited

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
int c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15;
        c1 = (int) C1.getValue();
        c2 = (int) C2.getValue();
        c3 = (int) C3.getValue();
        c4 = (int) C4.getValue();
        c5 = (int) C5.getValue();
        c6 = (int) C6.getValue();
        c7 = (int) C7.getValue();
        c8 = (int) C8.getValue();
        c9 = (int) C9.getValue();
        c10 = (int) C10.getValue();
        c11 = (int) C11.getValue();
        c12 = (int) C12.getValue();
        c13 = (int) C13.getValue();
        c14 = (int) C14.getValue();
        c15 = (int) C15.getValue();
       
        if(c1 > 0 || c2 > 0 || c3 > 0 || c4 > 0 || c5 > 0 || c6 > 0 || c7 > 0 || c8 > 0 || c9 > 0 || c10 > 0 || c11 > 0 || c12 > 0 || c13 > 0 || c14 > 0 || c15 > 0){
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
            stat = con.createStatement();
            String query1 = "Delete from cart;";
            stat.executeUpdate(query1);

            if (c1 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Mohanthal', 60," + c1 + ");";
                stat.executeUpdate(query);
            }
            if (c2 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Adadiya', 60," + c2 + ");";
                stat.executeUpdate(query);
            }
            if (c3 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Peda', 70," + c3 + ");";
                stat.executeUpdate(query);
            }
            if (c4 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Mesub', 75," + c4 + ");";
                stat.executeUpdate(query);
            }
            if (c5 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Kalakand', 75," + c5 + ");";
                stat.executeUpdate(query);
            }
            if (c6 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Keri no Ras', 85," + c6 + ");";
                stat.executeUpdate(query);
            }
            if (c7 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Barfi', 90," + c7 + ");";
                stat.executeUpdate(query);
            }
            if (c8 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Suterfeni', 100," + c8 + ");";
                stat.executeUpdate(query);
            }
            if (c9 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Ghevar', 115," + c9 + ");";
                stat.executeUpdate(query);
            }
            if (c10 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Malpua', 120," + c10 + ");";
                stat.executeUpdate(query);
            }
            if (c11 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Halwasan', 125," + c11 + ");";
                stat.executeUpdate(query);
            }
            if (c12 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Basundi (250ml)', 125," + c12 + ");";
                stat.executeUpdate(query);
            }
            if (c13 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Kopra Pak', 130," + c13 + ");";
                stat.executeUpdate(query);
            }
            if (c14 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Rasmalai', 140," + c14 + ");";
                stat.executeUpdate(query);
            }
            if (c15 > 0) {
                String query = "Insert into cart values ('Makhan Bhog', 'Ghari', 160," + c15 + ");";
                stat.executeUpdate(query);
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error in Cart Button", null, 2);
        }

int Ans = JOptionPane.showConfirmDialog(this, "<html><font color = green size = 15 face = rockwell>Do you want to add Items to Cart?", null, 0, -1);
if (Ans == JOptionPane.YES_OPTION) {
            Restaurants.Cart.main(null);
            this.dispose();
    }
    }
else
    JOptionPane.showMessageDialog(this, "<html><font color = red size = 15 face = rockwell>Select any Item", null, -1);
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBtnActionPerformed

    private void Add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add6ActionPerformed
        C6.setVisible(true);
        Add6.setVisible(false);
        C6.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add6ActionPerformed

    private void Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add5ActionPerformed
        C5.setVisible(true);
        Add5.setVisible(false);
        C5.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add5ActionPerformed

    private void Add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add4ActionPerformed
        C4.setVisible(true);
        Add4.setVisible(false);
        C4.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add4ActionPerformed

    private void Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add3ActionPerformed
        C3.setVisible(true);
        Add3.setVisible(false);
        C3.setValue(1);// TODO add your handling code here:
    }//GEN-LAST:event_Add3ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        C2.setVisible(true);
        Add2.setVisible(false);
        C2.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        C1.setVisible(true);
        Add1.setVisible(false);
        C1.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed

    private void Add7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add7ActionPerformed
        C7.setVisible(true);
        Add7.setVisible(false);
        C7.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add7ActionPerformed

    private void Add8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add8ActionPerformed
        C8.setVisible(true);
        Add8.setVisible(false);
        C8.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add8ActionPerformed

    private void Add9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add9ActionPerformed
        C9.setVisible(true);
        Add9.setVisible(false);
        C9.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add9ActionPerformed

    private void Add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add10ActionPerformed
        C10.setVisible(true);
        Add10.setVisible(false);
        C10.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add10ActionPerformed

    private void Add11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add11ActionPerformed
        C11.setVisible(true);
        Add11.setVisible(false);
        C11.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add11ActionPerformed

    private void Add12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add12ActionPerformed
        C12.setVisible(true);
        Add12.setVisible(false);
        C12.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add12ActionPerformed

    private void Add13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add13ActionPerformed
        C13.setVisible(true);
        Add13.setVisible(false);
        C13.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add13ActionPerformed

    private void Add14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add14ActionPerformed
        C14.setVisible(true);
        Add14.setVisible(false);
        C14.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add14ActionPerformed

    private void Add15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add15ActionPerformed
        C15.setVisible(true);
        Add15.setVisible(false);
        C15.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahemdabad_Makhan_Bhog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add10;
    private javax.swing.JButton Add11;
    private javax.swing.JButton Add12;
    private javax.swing.JButton Add13;
    private javax.swing.JButton Add14;
    private javax.swing.JButton Add15;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Add3;
    private javax.swing.JButton Add4;
    private javax.swing.JButton Add5;
    private javax.swing.JButton Add6;
    private javax.swing.JButton Add7;
    private javax.swing.JButton Add8;
    private javax.swing.JButton Add9;
    private javax.swing.JLabel Address;
    private javax.swing.JSpinner C1;
    private javax.swing.JSpinner C10;
    private javax.swing.JSpinner C11;
    private javax.swing.JSpinner C12;
    private javax.swing.JSpinner C13;
    private javax.swing.JSpinner C14;
    private javax.swing.JSpinner C15;
    private javax.swing.JSpinner C2;
    private javax.swing.JSpinner C3;
    private javax.swing.JSpinner C4;
    private javax.swing.JSpinner C5;
    private javax.swing.JSpinner C6;
    private javax.swing.JSpinner C7;
    private javax.swing.JSpinner C8;
    private javax.swing.JSpinner C9;
    private javax.swing.JButton CartBtn;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I10;
    private javax.swing.JLabel I11;
    private javax.swing.JLabel I12;
    private javax.swing.JLabel I13;
    private javax.swing.JLabel I14;
    private javax.swing.JLabel I15;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JLabel I5;
    private javax.swing.JLabel I6;
    private javax.swing.JLabel I7;
    private javax.swing.JLabel I8;
    private javax.swing.JLabel I9;
    private javax.swing.JSeparator IS1;
    private javax.swing.JSeparator IS10;
    private javax.swing.JSeparator IS11;
    private javax.swing.JSeparator IS12;
    private javax.swing.JSeparator IS13;
    private javax.swing.JSeparator IS14;
    private javax.swing.JSeparator IS15;
    private javax.swing.JSeparator IS2;
    private javax.swing.JSeparator IS3;
    private javax.swing.JSeparator IS4;
    private javax.swing.JSeparator IS5;
    private javax.swing.JSeparator IS6;
    private javax.swing.JSeparator IS7;
    private javax.swing.JSeparator IS8;
    private javax.swing.JSeparator IS9;
    private javax.swing.JLabel KB_Label;
    private javax.swing.JLabel LabelBack;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JLabel PALabel;
    private javax.swing.JLabel RestaurantLabel;
    private javax.swing.JSeparator S1;
    private javax.swing.JSeparator S2;
    private javax.swing.JSeparator S3;
    private javax.swing.JSeparator S4;
    private javax.swing.JLabel SigninLabel;
    private javax.swing.JPanel SweetPanel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
