/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurants;

import Project_Frames._2_Login;
import Project_Frames._3_Location;
import Project_Frames._4_Main_Order_Gujarat_Ahemdabad;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Ahemdabad_Vimal_Ice_Creams extends javax.swing.JFrame {
Connection con;
ResultSet rs;
Statement stat;
    /**
     * Creates new form Cake Square
     */
    public Ahemdabad_Vimal_Ice_Creams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CartBtn = new javax.swing.JButton();
        KBLabel = new javax.swing.JLabel();
        RestaurantLabel = new javax.swing.JLabel();
        LocationLabel = new javax.swing.JLabel();
        SigninLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        LabelBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Main_panel = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        S1 = new javax.swing.JSeparator();
        S2 = new javax.swing.JSeparator();
        S3 = new javax.swing.JSeparator();
        S4 = new javax.swing.JSeparator();
        PacksPanel = new javax.swing.JPanel();
        Add1 = new javax.swing.JButton();
        C1 = new javax.swing.JSpinner();
        I1 = new javax.swing.JLabel();
        IS1 = new javax.swing.JSeparator();
        Add2 = new javax.swing.JButton();
        C2 = new javax.swing.JSpinner();
        I2 = new javax.swing.JLabel();
        IS2 = new javax.swing.JSeparator();
        Add3 = new javax.swing.JButton();
        C3 = new javax.swing.JSpinner();
        I3 = new javax.swing.JLabel();
        IS3 = new javax.swing.JSeparator();
        Add4 = new javax.swing.JButton();
        C4 = new javax.swing.JSpinner();
        I4 = new javax.swing.JLabel();
        IS4 = new javax.swing.JSeparator();
        Add5 = new javax.swing.JButton();
        C5 = new javax.swing.JSpinner();
        I5 = new javax.swing.JLabel();
        IS5 = new javax.swing.JSeparator();
        Add6 = new javax.swing.JButton();
        C6 = new javax.swing.JSpinner();
        I6 = new javax.swing.JLabel();
        IS6 = new javax.swing.JSeparator();
        Add7 = new javax.swing.JButton();
        C7 = new javax.swing.JSpinner();
        I7 = new javax.swing.JLabel();
        IS7 = new javax.swing.JSeparator();
        Add8 = new javax.swing.JButton();
        C8 = new javax.swing.JSpinner();
        I8 = new javax.swing.JLabel();
        IS8 = new javax.swing.JSeparator();
        Add9 = new javax.swing.JButton();
        C9 = new javax.swing.JSpinner();
        I9 = new javax.swing.JLabel();
        IS9 = new javax.swing.JSeparator();
        Add10 = new javax.swing.JButton();
        C10 = new javax.swing.JSpinner();
        I10 = new javax.swing.JLabel();
        IS10 = new javax.swing.JSeparator();
        Add11 = new javax.swing.JButton();
        C11 = new javax.swing.JSpinner();
        I11 = new javax.swing.JLabel();
        IS11 = new javax.swing.JSeparator();
        Add12 = new javax.swing.JButton();
        C12 = new javax.swing.JSpinner();
        I12 = new javax.swing.JLabel();
        IS12 = new javax.swing.JSeparator();
        Add13 = new javax.swing.JButton();
        C13 = new javax.swing.JSpinner();
        I13 = new javax.swing.JLabel();
        IS13 = new javax.swing.JSeparator();
        Add14 = new javax.swing.JButton();
        C14 = new javax.swing.JSpinner();
        I14 = new javax.swing.JLabel();
        IS14 = new javax.swing.JSeparator();
        SpecialPanel = new javax.swing.JPanel();
        Add15 = new javax.swing.JButton();
        C15 = new javax.swing.JSpinner();
        I15 = new javax.swing.JLabel();
        IS15 = new javax.swing.JSeparator();
        Add16 = new javax.swing.JButton();
        C16 = new javax.swing.JSpinner();
        I16 = new javax.swing.JLabel();
        IS16 = new javax.swing.JSeparator();
        Add17 = new javax.swing.JButton();
        C17 = new javax.swing.JSpinner();
        I17 = new javax.swing.JLabel();
        IS17 = new javax.swing.JSeparator();
        Add18 = new javax.swing.JButton();
        C18 = new javax.swing.JSpinner();
        I18 = new javax.swing.JLabel();
        IS18 = new javax.swing.JSeparator();
        Add19 = new javax.swing.JButton();
        C19 = new javax.swing.JSpinner();
        I19 = new javax.swing.JLabel();
        IS19 = new javax.swing.JSeparator();
        Add20 = new javax.swing.JButton();
        C20 = new javax.swing.JSpinner();
        I20 = new javax.swing.JLabel();
        IS20 = new javax.swing.JSeparator();
        Add21 = new javax.swing.JButton();
        C21 = new javax.swing.JSpinner();
        IS21 = new javax.swing.JSeparator();
        I21 = new javax.swing.JLabel();
        Add22 = new javax.swing.JButton();
        C22 = new javax.swing.JSpinner();
        IS22 = new javax.swing.JSeparator();
        I22 = new javax.swing.JLabel();
        Add23 = new javax.swing.JButton();
        C23 = new javax.swing.JSpinner();
        IS23 = new javax.swing.JSeparator();
        I23 = new javax.swing.JLabel();
        Add24 = new javax.swing.JButton();
        C24 = new javax.swing.JSpinner();
        IS24 = new javax.swing.JSeparator();
        I24 = new javax.swing.JLabel();
        Add25 = new javax.swing.JButton();
        C25 = new javax.swing.JSpinner();
        IS25 = new javax.swing.JSeparator();
        I25 = new javax.swing.JLabel();
        Add26 = new javax.swing.JButton();
        C26 = new javax.swing.JSpinner();
        IS26 = new javax.swing.JSeparator();
        I26 = new javax.swing.JLabel();
        Add27 = new javax.swing.JButton();
        C27 = new javax.swing.JSpinner();
        IS27 = new javax.swing.JSeparator();
        I27 = new javax.swing.JLabel();
        Add28 = new javax.swing.JButton();
        C28 = new javax.swing.JSpinner();
        IS28 = new javax.swing.JSeparator();
        I28 = new javax.swing.JLabel();
        PackLabel = new javax.swing.JLabel();
        SpecialLabel = new javax.swing.JLabel();
        KB_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vimal Ice Creams");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartBtn.setBackground(new java.awt.Color(0, 153, 204));
        CartBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        CartBtn.setText("Cart");
        CartBtn.setRequestFocusEnabled(false);
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 140, -1));

        KBLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        KBLabel.setForeground(new java.awt.Color(51, 51, 51));
        KBLabel.setText("Vimal Ice Creams");
        jPanel1.add(KBLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 40));

        RestaurantLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        RestaurantLabel.setForeground(new java.awt.Color(142, 142, 142));
        RestaurantLabel.setText("Restaurant(Surat) /");
        RestaurantLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestaurantLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseExited(evt);
            }
        });
        jPanel1.add(RestaurantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 40));

        LocationLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        LocationLabel.setForeground(new java.awt.Color(142, 142, 142));
        LocationLabel.setText("Location /");
        LocationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LocationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LocationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LocationLabelMouseExited(evt);
            }
        });
        jPanel1.add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 40));

        SigninLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        SigninLabel.setForeground(new java.awt.Color(142, 142, 142));
        SigninLabel.setText("Sign in /");
        SigninLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SigninLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SigninLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SigninLabelMouseExited(evt);
            }
        });
        jPanel1.add(SigninLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, -1, 40));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Gujarat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/Foodiezz.png"))); // NOI18N
        jPanel1.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        Address.setFont(new java.awt.Font("Narkisim", 0, 24)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Papyrus", 0, 24))); // NOI18N
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 460, 80));

        LabelBack.setOpaque(true);
        jPanel1.add(LabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1350, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(153, 153, 153));
        TypeLabel.setText("Packs");
        Main_panel.add(TypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        S1.setBackground(new java.awt.Color(102, 102, 102));
        S1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 10, 50));

        S2.setBackground(new java.awt.Color(102, 102, 102));
        S2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 10, 50));

        S3.setBackground(new java.awt.Color(102, 102, 102));
        S3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 10, 450));

        S4.setBackground(new java.awt.Color(102, 102, 102));
        Main_panel.add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 1050, 10));

        PacksPanel.setBackground(new java.awt.Color(255, 255, 255));
        PacksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add1.setBackground(new java.awt.Color(9, 101, 0));
        Add1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("ADD");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        C1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        I1.setBackground(new java.awt.Color(255, 255, 255));
        I1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/1 peppy_pineapple 120.png"))); // NOI18N
        I1.setText("<html>Peppy Pineapple (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.120 ");
        I1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I1.setIconTextGap(80);
        I1.setRequestFocusEnabled(false);
        I1.setVerifyInputWhenFocusTarget(false);
        I1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 220));

        IS1.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1050, 10));

        Add2.setBackground(new java.awt.Color(9, 101, 0));
        Add2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("ADD");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 80, 30));

        C2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 80, 30));

        I2.setBackground(new java.awt.Color(255, 255, 255));
        I2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/2 tangy_orange 120.png"))); // NOI18N
        I2.setText("<html>Tangy Orange (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.120 ");
        I2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I2.setIconTextGap(80);
        I2.setRequestFocusEnabled(false);
        I2.setVerifyInputWhenFocusTarget(false);
        I2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1050, 220));

        IS2.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1050, 10));

        Add3.setBackground(new java.awt.Color(9, 101, 0));
        Add3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("ADD");
        Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add3ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 80, 30));

        C3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 80, 30));

        I3.setBackground(new java.awt.Color(255, 255, 255));
        I3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/3 strawberry_wonder 120.png"))); // NOI18N
        I3.setText("<html>Strawberry Wonder (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.120 ");
        I3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I3.setIconTextGap(80);
        I3.setRequestFocusEnabled(false);
        I3.setVerifyInputWhenFocusTarget(false);
        I3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1050, 220));

        IS3.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1050, 10));

        Add4.setBackground(new java.awt.Color(9, 101, 0));
        Add4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));
        Add4.setText("ADD");
        Add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add4ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 740, 80, 30));

        C4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 740, 80, 30));

        I4.setBackground(new java.awt.Color(255, 255, 255));
        I4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/4 classic_pista 130.png"))); // NOI18N
        I4.setText("<html>Classic Pista (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.130");
        I4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I4.setIconTextGap(80);
        I4.setRequestFocusEnabled(false);
        I4.setVerifyInputWhenFocusTarget(false);
        I4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1050, 220));

        IS4.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 940, 1050, 10));

        Add5.setBackground(new java.awt.Color(9, 101, 0));
        Add5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));
        Add5.setText("ADD");
        Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add5ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 980, 80, 30));

        C5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 980, 80, 30));

        I5.setBackground(new java.awt.Color(255, 255, 255));
        I5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/5 classic_butter_scotch 130.png"))); // NOI18N
        I5.setText("<html>Classic Butter Scotch (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.130");
        I5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I5.setIconTextGap(80);
        I5.setRequestFocusEnabled(false);
        I5.setVerifyInputWhenFocusTarget(false);
        I5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 1050, 220));

        IS5.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1180, 1050, 10));

        Add6.setBackground(new java.awt.Color(9, 101, 0));
        Add6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));
        Add6.setText("ADD");
        Add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add6ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1220, 80, 30));

        C6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1220, 80, 30));

        I6.setBackground(new java.awt.Color(255, 255, 255));
        I6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/6 sahi_pan 135.png"))); // NOI18N
        I6.setText("<html>Sahi Pan (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.135");
        I6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I6.setIconTextGap(80);
        I6.setRequestFocusEnabled(false);
        I6.setVerifyInputWhenFocusTarget(false);
        I6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1200, 1050, 220));

        IS6.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1420, 1050, 10));

        Add7.setBackground(new java.awt.Color(9, 101, 0));
        Add7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add7.setForeground(new java.awt.Color(255, 255, 255));
        Add7.setText("ADD");
        Add7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add7ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1450, 80, 30));

        C7.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1450, 80, 30));

        I7.setBackground(new java.awt.Color(255, 255, 255));
        I7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/7 top_choice 145.png"))); // NOI18N
        I7.setText("<html>Top Choice (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.145");
        I7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I7.setIconTextGap(80);
        I7.setRequestFocusEnabled(false);
        I7.setVerifyInputWhenFocusTarget(false);
        I7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1430, 1050, 220));

        IS7.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1650, 1050, 10));

        Add8.setBackground(new java.awt.Color(9, 101, 0));
        Add8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add8.setForeground(new java.awt.Color(255, 255, 255));
        Add8.setText("ADD");
        Add8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add8ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1690, 80, 30));

        C8.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1690, 80, 30));

        I8.setBackground(new java.awt.Color(255, 255, 255));
        I8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/8 digestive_zero_sugar_vanilla 160.png"))); // NOI18N
        I8.setText("<html>Digestive Zero Sugar Vanilla (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.160");
        I8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I8.setIconTextGap(80);
        I8.setRequestFocusEnabled(false);
        I8.setVerifyInputWhenFocusTarget(false);
        I8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1670, 1050, 220));

        IS8.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1890, 1050, 10));

        Add9.setBackground(new java.awt.Color(9, 101, 0));
        Add9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add9.setForeground(new java.awt.Color(255, 255, 255));
        Add9.setText("ADD");
        Add9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add9ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1930, 80, 30));

        C9.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1930, 80, 30));

        I9.setBackground(new java.awt.Color(255, 255, 255));
        I9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/9 digestive_zero_sugar_anjeer 175.png"))); // NOI18N
        I9.setText("<html>Digestive Zero Sugar Anjeer (750ml)<br><font color = gray >Packs</font><br><br><b>Rs.175");
        I9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I9.setIconTextGap(80);
        I9.setRequestFocusEnabled(false);
        I9.setVerifyInputWhenFocusTarget(false);
        I9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1910, 1050, 220));

        IS9.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2130, 1050, 10));

        Add10.setBackground(new java.awt.Color(9, 101, 0));
        Add10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add10.setForeground(new java.awt.Color(255, 255, 255));
        Add10.setText("ADD");
        Add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add10ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2160, 80, 30));

        C10.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2160, 80, 30));

        I10.setBackground(new java.awt.Color(255, 255, 255));
        I10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/10 lychee_coconut 210.png"))); // NOI18N
        I10.setText("<html>Lychee Coconut (1.5 Ltrs)<br><font color = gray >Packs</font><br><br><b>Rs.210");
        I10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I10.setIconTextGap(0);
        I10.setRequestFocusEnabled(false);
        I10.setVerifyInputWhenFocusTarget(false);
        I10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2140, 1050, 220));

        IS10.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2360, 1050, 10));

        Add11.setBackground(new java.awt.Color(9, 101, 0));
        Add11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add11.setForeground(new java.awt.Color(255, 255, 255));
        Add11.setText("ADD");
        Add11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add11ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2390, 80, 30));

        C11.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2390, 80, 30));

        I11.setBackground(new java.awt.Color(255, 255, 255));
        I11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/11 nutts_berries 220.png"))); // NOI18N
        I11.setText("<html>Nutts Berries (1.5 Ltrs)<br><font color = gray >Packs</font><br><br><b>Rs.220");
        I11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I11.setIconTextGap(0);
        I11.setRequestFocusEnabled(false);
        I11.setVerifyInputWhenFocusTarget(false);
        I11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2370, 1050, 220));

        IS11.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2590, 1050, 10));

        Add12.setBackground(new java.awt.Color(9, 101, 0));
        Add12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add12.setForeground(new java.awt.Color(255, 255, 255));
        Add12.setText("ADD");
        Add12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add12ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2620, 80, 30));

        C12.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2620, 80, 30));

        I12.setBackground(new java.awt.Color(255, 255, 255));
        I12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/12 pistachio_praline 230.png"))); // NOI18N
        I12.setText("<html>Pistachio Praline (1.5 Ltrs)<br><font color = gray >Packs</font><br><br><b>Rs.230");
        I12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I12.setIconTextGap(0);
        I12.setRequestFocusEnabled(false);
        I12.setVerifyInputWhenFocusTarget(false);
        I12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2600, 1050, 220));

        IS12.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2820, 1050, 10));

        Add13.setBackground(new java.awt.Color(9, 101, 0));
        Add13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add13.setForeground(new java.awt.Color(255, 255, 255));
        Add13.setText("ADD");
        Add13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add13ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2850, 80, 30));

        C13.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2850, 80, 30));

        I13.setBackground(new java.awt.Color(255, 255, 255));
        I13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/13 arabian_delight 245.png"))); // NOI18N
        I13.setText("<html>Arabian Delight (1.5 Ltrs)<br><font color = gray >Packs</font><br><br><b>Rs.245");
        I13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I13.setIconTextGap(0);
        I13.setRequestFocusEnabled(false);
        I13.setVerifyInputWhenFocusTarget(false);
        I13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2830, 1050, 220));

        IS13.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3050, 1050, 10));

        Add14.setBackground(new java.awt.Color(9, 101, 0));
        Add14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add14.setForeground(new java.awt.Color(255, 255, 255));
        Add14.setText("ADD");
        Add14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add14ActionPerformed(evt);
            }
        });
        PacksPanel.add(Add14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 3080, 80, 30));

        C14.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PacksPanel.add(C14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 3080, 80, 30));

        I14.setBackground(new java.awt.Color(255, 255, 255));
        I14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Packs/14 california_chocolate 260.png"))); // NOI18N
        I14.setText("<html>California Chocolate (1.5 Ltrs)<br><font color = gray >Packs</font><br><br><b>Rs.260");
        I14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I14.setIconTextGap(0);
        I14.setRequestFocusEnabled(false);
        I14.setVerifyInputWhenFocusTarget(false);
        I14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PacksPanel.add(I14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3060, 1050, 220));

        IS14.setBackground(new java.awt.Color(224, 224, 224));
        PacksPanel.add(IS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3280, 1050, 10));

        Main_panel.add(PacksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 1050, 3280));

        SpecialPanel.setBackground(new java.awt.Color(255, 255, 255));
        SpecialPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add15.setBackground(new java.awt.Color(9, 101, 0));
        Add15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add15.setForeground(new java.awt.Color(255, 255, 255));
        Add15.setText("ADD");
        Add15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add15ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        C15.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        I15.setBackground(new java.awt.Color(255, 255, 255));
        I15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/1 strawberry_must 25.png"))); // NOI18N
        I15.setText("<html>Strawberry<br><font color = gray >Sundae</font><br><br><b>Rs.25");
        I15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I15.setIconTextGap(15);
        I15.setRequestFocusEnabled(false);
        I15.setVerifyInputWhenFocusTarget(false);
        I15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 220));

        IS15.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1050, 10));

        Add16.setBackground(new java.awt.Color(9, 101, 0));
        Add16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add16.setForeground(new java.awt.Color(255, 255, 255));
        Add16.setText("ADD");
        Add16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add16ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 80, 30));

        C16.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 80, 30));

        I16.setBackground(new java.awt.Color(255, 255, 255));
        I16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/2 chocolate_must 25.png"))); // NOI18N
        I16.setText("<html>Chocolate<br><font color = gray >Sundae</font><br><br><b>Rs.25");
        I16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I16.setIconTextGap(15);
        I16.setRequestFocusEnabled(false);
        I16.setVerifyInputWhenFocusTarget(false);
        I16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1050, 220));

        IS16.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1050, 10));

        Add17.setBackground(new java.awt.Color(9, 101, 0));
        Add17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add17.setForeground(new java.awt.Color(255, 255, 255));
        Add17.setText("ADD");
        Add17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add17ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 80, 30));

        C17.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 80, 30));

        I17.setBackground(new java.awt.Color(255, 255, 255));
        I17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/3 nutty_frutty_cassatta  35.png"))); // NOI18N
        I17.setText("<html>Nutty Frutty Cassatta<br><font color = gray >Ice Cream</font><br><br><b>Rs.35");
        I17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I17.setIconTextGap(100);
        I17.setRequestFocusEnabled(false);
        I17.setVerifyInputWhenFocusTarget(false);
        I17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1050, 220));

        IS17.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1050, 10));

        Add18.setBackground(new java.awt.Color(9, 101, 0));
        Add18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add18.setForeground(new java.awt.Color(255, 255, 255));
        Add18.setText("ADD");
        Add18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add18ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 80, 30));

        C18.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 80, 30));

        I18.setBackground(new java.awt.Color(255, 255, 255));
        I18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/4 sandwich_ice_cream 45.png"))); // NOI18N
        I18.setText("<html>Sandwich<br><font color = gray >Ice Cream</font><br><br><b>Rs.45");
        I18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I18.setIconTextGap(100);
        I18.setRequestFocusEnabled(false);
        I18.setVerifyInputWhenFocusTarget(false);
        I18.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1050, 220));

        IS18.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, 1050, 10));

        Add19.setBackground(new java.awt.Color(9, 101, 0));
        Add19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add19.setForeground(new java.awt.Color(255, 255, 255));
        Add19.setText("ADD");
        Add19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add19ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 940, 80, 30));

        C19.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 940, 80, 30));

        I19.setBackground(new java.awt.Color(255, 255, 255));
        I19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/5 vanilla_cookies 60.png"))); // NOI18N
        I19.setText("<html>Vanilla Cookie<br><font color = gray >Ice Cream</font><br><br><b>Rs.60");
        I19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I19.setIconTextGap(100);
        I19.setRequestFocusEnabled(false);
        I19.setVerifyInputWhenFocusTarget(false);
        I19.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 920, 1050, 220));

        IS19.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1140, 1050, 10));

        Add20.setBackground(new java.awt.Color(9, 101, 0));
        Add20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add20.setForeground(new java.awt.Color(255, 255, 255));
        Add20.setText("ADD");
        Add20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add20ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1170, 80, 30));

        C20.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1170, 80, 30));

        I20.setBackground(new java.awt.Color(255, 255, 255));
        I20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/6 chocolate_cookies 65.png"))); // NOI18N
        I20.setText("<html>Chocolate Cookie<br><font color = gray >Ice Cream</font><br><br><b>Rs.65");
        I20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I20.setIconTextGap(100);
        I20.setRequestFocusEnabled(false);
        I20.setVerifyInputWhenFocusTarget(false);
        I20.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1150, 1050, 220));

        IS20.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1370, 1050, 10));

        Add21.setBackground(new java.awt.Color(9, 101, 0));
        Add21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add21.setForeground(new java.awt.Color(255, 255, 255));
        Add21.setText("ADD");
        Add21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add21ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1410, 80, 30));

        C21.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1410, 80, 30));

        IS21.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1610, 1050, 10));

        I21.setBackground(new java.awt.Color(255, 255, 255));
        I21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/7 black_forest 80.png"))); // NOI18N
        I21.setText("<html>Black Forest<br><font color = gray >Pastries</font><br><br><b>Rs.80");
        I21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I21.setIconTextGap(100);
        I21.setRequestFocusEnabled(false);
        I21.setVerifyInputWhenFocusTarget(false);
        I21.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1390, 1050, 220));

        Add22.setBackground(new java.awt.Color(9, 101, 0));
        Add22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add22.setForeground(new java.awt.Color(255, 255, 255));
        Add22.setText("ADD");
        Add22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add22ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add22, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1640, 80, 30));

        C22.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C22, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1640, 80, 30));

        IS22.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1840, 1050, 10));

        I22.setBackground(new java.awt.Color(255, 255, 255));
        I22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/8 red_velvet 85.png"))); // NOI18N
        I22.setText("<html>Red Velvet<br><font color = gray >Pastries</font><br><br><b>Rs.85");
        I22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I22.setIconTextGap(100);
        I22.setRequestFocusEnabled(false);
        I22.setVerifyInputWhenFocusTarget(false);
        I22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1620, 1050, 220));

        Add23.setBackground(new java.awt.Color(9, 101, 0));
        Add23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add23.setForeground(new java.awt.Color(255, 255, 255));
        Add23.setText("ADD");
        Add23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add23ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1870, 80, 30));

        C23.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1870, 80, 30));

        IS23.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2070, 1050, 10));

        I23.setBackground(new java.awt.Color(255, 255, 255));
        I23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/9 twin_sundae 110.png"))); // NOI18N
        I23.setText("<html>Twin (Mango/Strawberry)<br><font color = gray >Sandae</font><br><br><b>Rs.110");
        I23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I23.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I23.setIconTextGap(20);
        I23.setRequestFocusEnabled(false);
        I23.setVerifyInputWhenFocusTarget(false);
        I23.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1850, 1050, 220));

        Add24.setBackground(new java.awt.Color(9, 101, 0));
        Add24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add24.setForeground(new java.awt.Color(255, 255, 255));
        Add24.setText("ADD");
        Add24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add24ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2120, 80, 30));

        C24.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2120, 80, 30));

        IS24.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2320, 1050, 10));

        I24.setBackground(new java.awt.Color(255, 255, 255));
        I24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/10 choco_brownie_fudge 130.png"))); // NOI18N
        I24.setText("<html>Choco Brownie Fudge<br><font color = gray >Ice Cream</font><br><br><b>Rs.130");
        I24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I24.setIconTextGap(20);
        I24.setRequestFocusEnabled(false);
        I24.setVerifyInputWhenFocusTarget(false);
        I24.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2100, 1050, 220));

        Add25.setBackground(new java.awt.Color(9, 101, 0));
        Add25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add25.setForeground(new java.awt.Color(255, 255, 255));
        Add25.setText("ADD");
        Add25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add25ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2360, 80, 30));

        C25.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2360, 80, 30));

        IS25.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2560, 1050, 10));

        I25.setBackground(new java.awt.Color(255, 255, 255));
        I25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/11 cheese_pineapple_cake 160.png"))); // NOI18N
        I25.setText("<html>Cheese Pineapple (500g)<br><font color = gray >Cake</font><br><br><b>Rs.160");
        I25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I25.setIconTextGap(100);
        I25.setRequestFocusEnabled(false);
        I25.setVerifyInputWhenFocusTarget(false);
        I25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2340, 1050, 220));

        Add26.setBackground(new java.awt.Color(9, 101, 0));
        Add26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add26.setForeground(new java.awt.Color(255, 255, 255));
        Add26.setText("ADD");
        Add26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add26ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add26, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2600, 80, 30));

        C26.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C26, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2600, 80, 30));

        IS26.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2800, 1050, 10));

        I26.setBackground(new java.awt.Color(255, 255, 255));
        I26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/12 cheese_strawberry_cake 160.png"))); // NOI18N
        I26.setText("<html>Cheese Strawberry (500g)<br><font color = gray >Cake</font><br><br><b>Rs.160");
        I26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I26.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I26.setIconTextGap(100);
        I26.setRequestFocusEnabled(false);
        I26.setVerifyInputWhenFocusTarget(false);
        I26.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2580, 1050, 220));

        Add27.setBackground(new java.awt.Color(9, 101, 0));
        Add27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add27.setForeground(new java.awt.Color(255, 255, 255));
        Add27.setText("ADD");
        Add27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add27ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add27, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2840, 80, 30));

        C27.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C27, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2840, 80, 30));

        IS27.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3040, 1050, 10));

        I27.setBackground(new java.awt.Color(255, 255, 255));
        I27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/13 black_forest_cake 210.png"))); // NOI18N
        I27.setText("<html>Black Forest (500g)<br><font color = gray >Cake</font><br><br><b>Rs.210");
        I27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I27.setIconTextGap(100);
        I27.setRequestFocusEnabled(false);
        I27.setVerifyInputWhenFocusTarget(false);
        I27.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2820, 1050, 220));

        Add28.setBackground(new java.awt.Color(9, 101, 0));
        Add28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add28.setForeground(new java.awt.Color(255, 255, 255));
        Add28.setText("ADD");
        Add28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add28ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add28, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 3080, 80, 30));

        C28.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpecialPanel.add(C28, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 3080, 80, 30));

        IS28.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3280, 1050, 10));

        I28.setBackground(new java.awt.Color(255, 255, 255));
        I28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Vimal Ice Creams(Ahmd)/Special/14 gold_rush_cake 220.png"))); // NOI18N
        I28.setText("<html>Gold Rush (500g)<br><font color = gray >Cake</font><br><br><b>Rs.220");
        I28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I28.setIconTextGap(100);
        I28.setRequestFocusEnabled(false);
        I28.setVerifyInputWhenFocusTarget(false);
        I28.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3060, 1050, 220));

        Main_panel.add(SpecialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 1050, 3280));

        PackLabel.setBackground(new java.awt.Color(255, 255, 255));
        PackLabel.setFont(new java.awt.Font("Rockwell", 1, 28)); // NOI18N
        PackLabel.setForeground(new java.awt.Color(153, 153, 153));
        PackLabel.setText("Packs");
        PackLabel.setOpaque(true);
        PackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PackLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PackLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PackLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PackLabelMouseReleased(evt);
            }
        });
        Main_panel.add(PackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, -1));

        SpecialLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpecialLabel.setFont(new java.awt.Font("Rockwell", 1, 28)); // NOI18N
        SpecialLabel.setForeground(new java.awt.Color(153, 153, 153));
        SpecialLabel.setText("Special");
        SpecialLabel.setOpaque(true);
        SpecialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SpecialLabelMousePressed(evt);
            }
        });
        Main_panel.add(SpecialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 190, -1));

        KB_Label.setBackground(new java.awt.Color(0, 15, 40));
        KB_Label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        KB_Label.setForeground(new java.awt.Color(255, 255, 255));
        KB_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restaurants/Ahemdabad/Vimal Ice Creams.png"))); // NOI18N
        KB_Label.setText("<html><font color = 'white' size = 15>Vimal Ice Creams</font><br><t><font color = gray>Ahemdabad</br><br>Ice Creams and Cake</font></br><br><br><br>4.5 / 5 <t> <t> <t><t> <t> <t> <t> <t><t> <t><t><t><t><t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>   <font color = white><t>    Rs.220</font><t>  <t>  <t> <t> <t>  <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>    <t> <t>  <t>  <t>   <t>  <t>  <t>  <t>  <t> <font color = white> 15 Minutes </font><br><font size=5 color = gray> 620+ Ratings<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t> <t>  <t> <t> <t>Cost For Two<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>  <t>    Delivery Time</font></br>"); // NOI18N
        KB_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new java.awt.Color(0, 15, 40)));
        KB_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KB_Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        KB_Label.setIconTextGap(20);
        KB_Label.setOpaque(true);
        KB_Label.setRequestFocusEnabled(false);
        KB_Label.setVerifyInputWhenFocusTarget(false);
        KB_Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(KB_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 280));

        jScrollPane1.setViewportView(Main_panel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1350, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setLocationRelativeTo(null);
        try{
    Class.forName("java.sql.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
    Statement stat = con.createStatement();
    String query = "Select * from Location;";
    rs = stat.executeQuery(query);
    while(rs.next()){
        String pn = rs.getString("Plot_no");
        String ar = rs.getString("Area");
        String land = rs.getString("Landmark");
        String pin = rs.getString("Pincode");
        String ct = rs.getString("City");
        String resi = rs.getString("Residence");
        Address.setText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
        Address.setToolTipText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
                
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, "Error in Adress",null,-2);
}
        
C1.setVisible(false);
C2.setVisible(false);
C3.setVisible(false);
C4.setVisible(false);
C5.setVisible(false);
C6.setVisible(false);
C7.setVisible(false);
C8.setVisible(false);
C9.setVisible(false);
C10.setVisible(false);
C11.setVisible(false);
C12.setVisible(false);
C13.setVisible(false);
C14.setVisible(false);
C15.setVisible(false);
C16.setVisible(false);
C17.setVisible(false);
C18.setVisible(false);
C19.setVisible(false);
C20.setVisible(false);
C21.setVisible(false);
C22.setVisible(false);
C23.setVisible(false);
C24.setVisible(false);
C25.setVisible(false);
C26.setVisible(false);
C27.setVisible(false);
C28.setVisible(false);

PacksPanel.setVisible(true);
SpecialPanel.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void PackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackLabelMouseEntered
PackLabel.setBackground(Color.GRAY);
PackLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_PackLabelMouseEntered

    private void PackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackLabelMouseExited
PackLabel.setBackground(Color.WHITE);
PackLabel.setForeground(Color.GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_PackLabelMouseExited

    private void SpecialLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseEntered
SpecialLabel.setBackground(Color.GRAY);
SpecialLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseEntered

    private void SpecialLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseExited
SpecialLabel.setBackground(Color.WHITE);
SpecialLabel.setForeground(Color.GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseExited

    private void SpecialLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseClicked
TypeLabel.setText("Special");
SpecialPanel.setVisible(true);
PacksPanel.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseClicked

    private void PackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackLabelMouseClicked
TypeLabel.setText("Packs");
PacksPanel.setVisible(true);
SpecialPanel.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_PackLabelMouseClicked

    private void PackLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackLabelMousePressed
PackLabel.setBackground(Color.DARK_GRAY);
PackLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_PackLabelMousePressed

    private void PackLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackLabelMouseReleased
PackLabel.setBackground(Color.GRAY);
PackLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_PackLabelMouseReleased

    private void SpecialLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMousePressed
SpecialLabel.setBackground(Color.DARK_GRAY);
SpecialLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMousePressed

    private void SpecialLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseReleased
SpecialLabel.setBackground(Color.GRAY);
SpecialLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseReleased

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
C1.setVisible(true);
Add1.setVisible(false);
C1.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed

    private void RestaurantLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = blue>Go back to Restaurants(Ahemdabad) Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            Project_Frames._4_Main_Order_Gujarat_Ahemdabad.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseClicked

    private void RestaurantLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseEntered
        RestaurantLabel.setText("<html><u>Restaurant(Ahemdabad)</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseEntered

    private void RestaurantLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseExited
        RestaurantLabel.setText("Restaurant(Ahemdabad) /");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseExited

    private void LocationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = Green>Go back to Location Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _3_Location.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseClicked

    private void LocationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseEntered
        LocationLabel.setText("<html><u>Location</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseEntered

    private void LocationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseExited
        LocationLabel.setText("Location /");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseExited

    private void SigninLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = orange>Go back to Sign in Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _2_Login.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseClicked

    private void SigninLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseEntered
        SigninLabel.setText("<html><u>Sign in</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseEntered

    private void SigninLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseExited
        SigninLabel.setText("Sign in /");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseExited

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
int c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36;
    
    c1 = (int) C1.getValue();
    c2 = (int) C2.getValue();
    c3 = (int) C3.getValue();
    c4 = (int) C4.getValue();
    c5 = (int) C5.getValue();
    c6 = (int) C6.getValue();
    c7 = (int) C7.getValue();
    c8 = (int) C8.getValue();
    c9 = (int) C9.getValue();
    c10 = (int) C10.getValue();
    c11 = (int) C11.getValue();
    c12 = (int) C12.getValue();
    c13 = (int) C13.getValue();
    c14 = (int) C14.getValue();
    c15 = (int) C15.getValue();
    c16 = (int) C16.getValue();
    c17 = (int) C17.getValue();
    c18 = (int) C18.getValue();
    c19 = (int) C19.getValue();
    c20 = (int) C20.getValue();
    c21 = (int) C21.getValue();
    c22 = (int) C22.getValue();
    c23 = (int) C23.getValue();
    c24 = (int) C24.getValue();
    c25 = (int) C25.getValue();
    c26 = (int) C26.getValue();
    c27 = (int) C27.getValue();
    c28 = (int) C28.getValue();
      
    if(c1 > 0 || c2 > 0 || c3 > 0 || c4 > 0 || c5 > 0 || c6 > 0 || c7 > 0 || c8 > 0 || c9 > 0 || c10 > 0 || c11 > 0 || c12 > 0 || c13 > 0 || c14 > 0 || c15 > 0 || c16 > 0 || c17 > 0 || c18 > 0 || c19 > 0 || c20 > 0 || c21 > 0 || c22 > 0 || c23 > 0 || c24 > 0 || c25 > 0 || c26 > 0 || c27 > 0 || c28 > 0){
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
            stat = con.createStatement();
            String query1 = "Delete from cart;";
            stat.executeUpdate(query1);

            if (c1 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Peppy Pineapple Pack (750ml)', 120," + c1 + ");";
                stat.executeUpdate(query);
            }if (c2 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Tangy Orange Pack (750ml)', 120," + c2 + ");";
                stat.executeUpdate(query);
            }if (c3 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Strawberry Wonder Pack (750ml)', 120," + c3 + ");";
                stat.executeUpdate(query);
            }if (c4 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Classic Pista Pack (750ml)', 130," + c4 + ");";
                stat.executeUpdate(query);
            }if (c5 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Classic Butterscotch Pack (750ml)', 130," + c5 + ");";
                stat.executeUpdate(query);
            }if (c6 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Sahi Pan Pack (750ml)', 135," + c6 + ");";
                stat.executeUpdate(query);
            }if (c7 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Top Choice Pack (750ml)', 145," + c7 + ");";
                stat.executeUpdate(query);
            }if (c8 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Digestive Zero Sugar Vanilla Pack (750ml)', 160," + c8 + ");";
                stat.executeUpdate(query);
            }if (c9 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Digestive Zero Sugar Anjeer Pack (750ml)', 175," + c9 + ");";
                stat.executeUpdate(query);
            }if (c10 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Lychee Coconut Pack (1.5 Ltrs)', 210," + c10 + ");";
                stat.executeUpdate(query);
            }if (c11 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Nutts Berries Pack (1.5 Ltrs)', 220," + c11 + ");";
                stat.executeUpdate(query);
            }if (c12 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Pistachio Praline Pack (1.5 Ltrs)', 230," + c12 + ");";
                stat.executeUpdate(query);
            }if (c13 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Arabian Delight Pack (1.5 Ltrs)', 245," + c13 + ");";
                stat.executeUpdate(query);
            }if (c14 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'California Chocolate Pack (1.5 Ltrs)', 260," + c14 + ");";
                stat.executeUpdate(query);
            }if (c15 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Strawberry Sundae', 25," + c15 + ");";
                stat.executeUpdate(query);
            }if (c16 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Chocolate Sundae', 25," + c16 + ");";
                stat.executeUpdate(query);
            }if (c17 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Nutty Frutty Cassatta', 35," + c17 + ");";
                stat.executeUpdate(query);
            }if (c18 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Sandwich Ice Cream', 45," + c18 + ");";
                stat.executeUpdate(query);
            }if (c19 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Vanilla Cookies', 60," + c19 + ");";
                stat.executeUpdate(query);
            }if (c20 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Chocolate Cookies', 65," + c20 + ");";
                stat.executeUpdate(query);
            }if (c21 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Black Forest Pastry', 80," + c21 + ");";
                stat.executeUpdate(query);
            }if (c22 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Red Velvet Pastry', 85," + c22 + ");";
                stat.executeUpdate(query);
            }if (c23 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Twin Sundae', 110," + c23 + ");";
                stat.executeUpdate(query);
            }if (c24 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Choco Brownie Fudge', 130," + c24 + ");";
                stat.executeUpdate(query);
            }if (c25 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Cheese Pineapple Cake (500g)', 160," + c25 + ");";
                stat.executeUpdate(query);
            }if (c26 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Cheese Strawberry Cake (500g)', 160," + c26 + ");";
                stat.executeUpdate(query);
            }if (c27 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Black Forest Cake (500g)', 210," + c27 + ");";
                stat.executeUpdate(query);
            }if (c28 > 0) {
                String query = "Insert into cart values ('Vimal Ice Creams', 'Gold Rush Cake (500g)', 220," + c28 + ");";
                stat.executeUpdate(query);
            }            
 
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error in Cart Button", null, 2);
        }
    }

    int Ans = JOptionPane.showConfirmDialog(this, "<html><font color = green size = 15 face = rockwell>Do you want to add Items to Cart?", null, 0, -1);
    if (Ans == JOptionPane.YES_OPTION) {
        Restaurants.Cart.main(null);
            this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBtnActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
C2.setVisible(true);
Add2.setVisible(false);
C2.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add3ActionPerformed
C3.setVisible(true);
Add3.setVisible(false);
C3.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add3ActionPerformed

    private void Add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add4ActionPerformed
C4.setVisible(true);
Add4.setVisible(false);
C4.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add4ActionPerformed

    private void Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add5ActionPerformed
C5.setVisible(true);
Add5.setVisible(false);
C5.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add5ActionPerformed

    private void Add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add6ActionPerformed
C6.setVisible(true);
Add6.setVisible(false);
C6.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add6ActionPerformed

    private void Add7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add7ActionPerformed
C7.setVisible(true);
Add7.setVisible(false);
C7.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add7ActionPerformed

    private void Add8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add8ActionPerformed
C8.setVisible(true);
Add8.setVisible(false);
C8.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add8ActionPerformed

    private void Add9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add9ActionPerformed
C9.setVisible(true);
Add9.setVisible(false);
C9.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add9ActionPerformed

    private void Add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add10ActionPerformed
C10.setVisible(true);
Add10.setVisible(false);
C10.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add10ActionPerformed

    private void Add19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add19ActionPerformed
C19.setVisible(true);
Add19.setVisible(false);
C19.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add19ActionPerformed

    private void Add20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add20ActionPerformed
C20.setVisible(true);
Add20.setVisible(false);
C20.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add20ActionPerformed

    private void Add21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add21ActionPerformed
C21.setVisible(true);
Add21.setVisible(false);
C21.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add21ActionPerformed

    private void Add22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add22ActionPerformed
C22.setVisible(true);
Add22.setVisible(false);
C22.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add22ActionPerformed

    private void Add11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add11ActionPerformed
C11.setVisible(true);
Add11.setVisible(false);
C11.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add11ActionPerformed

    private void Add12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add12ActionPerformed
C12.setVisible(true);
Add12.setVisible(false);
C12.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add12ActionPerformed

    private void Add13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add13ActionPerformed
C13.setVisible(true);
Add13.setVisible(false);
C13.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add13ActionPerformed

    private void Add14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add14ActionPerformed
C14.setVisible(true);
Add14.setVisible(false);
C14.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add14ActionPerformed

    private void Add15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add15ActionPerformed
C15.setVisible(true);
Add15.setVisible(false);
C15.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add15ActionPerformed

    private void Add16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add16ActionPerformed
C16.setVisible(true);
Add16.setVisible(false);
C16.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add16ActionPerformed

    private void Add17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add17ActionPerformed
C17.setVisible(true);
Add17.setVisible(false);
C17.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add17ActionPerformed

    private void Add18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add18ActionPerformed
C18.setVisible(true);
Add18.setVisible(false);
C18.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add18ActionPerformed

    private void Add23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add23ActionPerformed
C23.setVisible(true);
Add23.setVisible(false);
C23.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add23ActionPerformed

    private void Add24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add24ActionPerformed
C24.setVisible(true);
Add24.setVisible(false);
C24.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add24ActionPerformed

    private void Add25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add25ActionPerformed
C25.setVisible(true);
Add25.setVisible(false);
C25.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add25ActionPerformed

    private void Add26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add26ActionPerformed
C26.setVisible(true);
Add26.setVisible(false);
C26.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add26ActionPerformed

    private void Add27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add27ActionPerformed
C27.setVisible(true);
Add27.setVisible(false);
C27.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add27ActionPerformed

    private void Add28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add28ActionPerformed
C28.setVisible(true);
Add28.setVisible(false);
C28.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Vimal_Ice_Creams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Vimal_Ice_Creams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Vimal_Ice_Creams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Vimal_Ice_Creams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahemdabad_Vimal_Ice_Creams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add10;
    private javax.swing.JButton Add11;
    private javax.swing.JButton Add12;
    private javax.swing.JButton Add13;
    private javax.swing.JButton Add14;
    private javax.swing.JButton Add15;
    private javax.swing.JButton Add16;
    private javax.swing.JButton Add17;
    private javax.swing.JButton Add18;
    private javax.swing.JButton Add19;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Add20;
    private javax.swing.JButton Add21;
    private javax.swing.JButton Add22;
    private javax.swing.JButton Add23;
    private javax.swing.JButton Add24;
    private javax.swing.JButton Add25;
    private javax.swing.JButton Add26;
    private javax.swing.JButton Add27;
    private javax.swing.JButton Add28;
    private javax.swing.JButton Add3;
    private javax.swing.JButton Add4;
    private javax.swing.JButton Add5;
    private javax.swing.JButton Add6;
    private javax.swing.JButton Add7;
    private javax.swing.JButton Add8;
    private javax.swing.JButton Add9;
    private javax.swing.JLabel Address;
    private javax.swing.JSpinner C1;
    private javax.swing.JSpinner C10;
    private javax.swing.JSpinner C11;
    private javax.swing.JSpinner C12;
    private javax.swing.JSpinner C13;
    private javax.swing.JSpinner C14;
    private javax.swing.JSpinner C15;
    private javax.swing.JSpinner C16;
    private javax.swing.JSpinner C17;
    private javax.swing.JSpinner C18;
    private javax.swing.JSpinner C19;
    private javax.swing.JSpinner C2;
    private javax.swing.JSpinner C20;
    private javax.swing.JSpinner C21;
    private javax.swing.JSpinner C22;
    private javax.swing.JSpinner C23;
    private javax.swing.JSpinner C24;
    private javax.swing.JSpinner C25;
    private javax.swing.JSpinner C26;
    private javax.swing.JSpinner C27;
    private javax.swing.JSpinner C28;
    private javax.swing.JSpinner C3;
    private javax.swing.JSpinner C4;
    private javax.swing.JSpinner C5;
    private javax.swing.JSpinner C6;
    private javax.swing.JSpinner C7;
    private javax.swing.JSpinner C8;
    private javax.swing.JSpinner C9;
    private javax.swing.JButton CartBtn;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I10;
    private javax.swing.JLabel I11;
    private javax.swing.JLabel I12;
    private javax.swing.JLabel I13;
    private javax.swing.JLabel I14;
    private javax.swing.JLabel I15;
    private javax.swing.JLabel I16;
    private javax.swing.JLabel I17;
    private javax.swing.JLabel I18;
    private javax.swing.JLabel I19;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I20;
    private javax.swing.JLabel I21;
    private javax.swing.JLabel I22;
    private javax.swing.JLabel I23;
    private javax.swing.JLabel I24;
    private javax.swing.JLabel I25;
    private javax.swing.JLabel I26;
    private javax.swing.JLabel I27;
    private javax.swing.JLabel I28;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JLabel I5;
    private javax.swing.JLabel I6;
    private javax.swing.JLabel I7;
    private javax.swing.JLabel I8;
    private javax.swing.JLabel I9;
    private javax.swing.JSeparator IS1;
    private javax.swing.JSeparator IS10;
    private javax.swing.JSeparator IS11;
    private javax.swing.JSeparator IS12;
    private javax.swing.JSeparator IS13;
    private javax.swing.JSeparator IS14;
    private javax.swing.JSeparator IS15;
    private javax.swing.JSeparator IS16;
    private javax.swing.JSeparator IS17;
    private javax.swing.JSeparator IS18;
    private javax.swing.JSeparator IS19;
    private javax.swing.JSeparator IS2;
    private javax.swing.JSeparator IS20;
    private javax.swing.JSeparator IS21;
    private javax.swing.JSeparator IS22;
    private javax.swing.JSeparator IS23;
    private javax.swing.JSeparator IS24;
    private javax.swing.JSeparator IS25;
    private javax.swing.JSeparator IS26;
    private javax.swing.JSeparator IS27;
    private javax.swing.JSeparator IS28;
    private javax.swing.JSeparator IS3;
    private javax.swing.JSeparator IS4;
    private javax.swing.JSeparator IS5;
    private javax.swing.JSeparator IS6;
    private javax.swing.JSeparator IS7;
    private javax.swing.JSeparator IS8;
    private javax.swing.JSeparator IS9;
    private javax.swing.JLabel KBLabel;
    private javax.swing.JLabel KB_Label;
    private javax.swing.JLabel LabelBack;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JLabel PackLabel;
    private javax.swing.JPanel PacksPanel;
    private javax.swing.JLabel RestaurantLabel;
    private javax.swing.JSeparator S1;
    private javax.swing.JSeparator S2;
    private javax.swing.JSeparator S3;
    private javax.swing.JSeparator S4;
    private javax.swing.JLabel SigninLabel;
    private javax.swing.JLabel SpecialLabel;
    private javax.swing.JPanel SpecialPanel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
