/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurants;

import Project_Frames._2_Login;
import Project_Frames._3_Location;
import Project_Frames._4_Main_Order_Gujarat_Ahemdabad;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Ahemdabad_Breadliner extends javax.swing.JFrame {
Connection con;
ResultSet rs;
Statement stat;
    /**
     * Creates new form Cake Square
     */
    public Ahemdabad_Breadliner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CartBtn = new javax.swing.JButton();
        KBLabel = new javax.swing.JLabel();
        RestaurantLabel = new javax.swing.JLabel();
        LocationLabel = new javax.swing.JLabel();
        SigninLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        LabelBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Main_panel = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        S1 = new javax.swing.JSeparator();
        S2 = new javax.swing.JSeparator();
        S3 = new javax.swing.JSeparator();
        S4 = new javax.swing.JSeparator();
        CakesPanel = new javax.swing.JPanel();
        Add1 = new javax.swing.JButton();
        C1 = new javax.swing.JSpinner();
        I1 = new javax.swing.JLabel();
        IS1 = new javax.swing.JSeparator();
        Add2 = new javax.swing.JButton();
        C2 = new javax.swing.JSpinner();
        I2 = new javax.swing.JLabel();
        IS2 = new javax.swing.JSeparator();
        Add3 = new javax.swing.JButton();
        C3 = new javax.swing.JSpinner();
        I3 = new javax.swing.JLabel();
        IS3 = new javax.swing.JSeparator();
        Add4 = new javax.swing.JButton();
        C4 = new javax.swing.JSpinner();
        I4 = new javax.swing.JLabel();
        IS4 = new javax.swing.JSeparator();
        Add5 = new javax.swing.JButton();
        C5 = new javax.swing.JSpinner();
        I5 = new javax.swing.JLabel();
        IS5 = new javax.swing.JSeparator();
        Add6 = new javax.swing.JButton();
        C6 = new javax.swing.JSpinner();
        I6 = new javax.swing.JLabel();
        IS6 = new javax.swing.JSeparator();
        Add7 = new javax.swing.JButton();
        C7 = new javax.swing.JSpinner();
        I7 = new javax.swing.JLabel();
        IS7 = new javax.swing.JSeparator();
        Add8 = new javax.swing.JButton();
        C8 = new javax.swing.JSpinner();
        I8 = new javax.swing.JLabel();
        IS8 = new javax.swing.JSeparator();
        Add9 = new javax.swing.JButton();
        C9 = new javax.swing.JSpinner();
        I9 = new javax.swing.JLabel();
        IS9 = new javax.swing.JSeparator();
        Add10 = new javax.swing.JButton();
        C10 = new javax.swing.JSpinner();
        I10 = new javax.swing.JLabel();
        IS10 = new javax.swing.JSeparator();
        SpecialPanel = new javax.swing.JPanel();
        Add11 = new javax.swing.JButton();
        C11 = new javax.swing.JSpinner();
        I11 = new javax.swing.JLabel();
        IS11 = new javax.swing.JSeparator();
        Add12 = new javax.swing.JButton();
        C12 = new javax.swing.JSpinner();
        I12 = new javax.swing.JLabel();
        IS12 = new javax.swing.JSeparator();
        Add13 = new javax.swing.JButton();
        C13 = new javax.swing.JSpinner();
        I13 = new javax.swing.JLabel();
        IS13 = new javax.swing.JSeparator();
        Add14 = new javax.swing.JButton();
        C14 = new javax.swing.JSpinner();
        I14 = new javax.swing.JLabel();
        IS14 = new javax.swing.JSeparator();
        Add15 = new javax.swing.JButton();
        C15 = new javax.swing.JSpinner();
        I15 = new javax.swing.JLabel();
        IS15 = new javax.swing.JSeparator();
        Add16 = new javax.swing.JButton();
        C16 = new javax.swing.JSpinner();
        I16 = new javax.swing.JLabel();
        IS16 = new javax.swing.JSeparator();
        Add17 = new javax.swing.JButton();
        C17 = new javax.swing.JSpinner();
        I17 = new javax.swing.JLabel();
        IS17 = new javax.swing.JSeparator();
        Add18 = new javax.swing.JButton();
        C18 = new javax.swing.JSpinner();
        I18 = new javax.swing.JLabel();
        IS18 = new javax.swing.JSeparator();
        Add19 = new javax.swing.JButton();
        C19 = new javax.swing.JSpinner();
        I19 = new javax.swing.JLabel();
        IS19 = new javax.swing.JSeparator();
        Add20 = new javax.swing.JButton();
        C20 = new javax.swing.JSpinner();
        I20 = new javax.swing.JLabel();
        IS20 = new javax.swing.JSeparator();
        CakeLabel = new javax.swing.JLabel();
        SpecialLabel = new javax.swing.JLabel();
        KB_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Breadliner");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartBtn.setBackground(new java.awt.Color(0, 153, 204));
        CartBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        CartBtn.setText("Cart");
        CartBtn.setRequestFocusEnabled(false);
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 140, -1));

        KBLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        KBLabel.setForeground(new java.awt.Color(51, 51, 51));
        KBLabel.setText("Breadliner");
        jPanel1.add(KBLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 40));

        RestaurantLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        RestaurantLabel.setForeground(new java.awt.Color(142, 142, 142));
        RestaurantLabel.setText("Restaurant(Surat) /");
        RestaurantLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestaurantLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseExited(evt);
            }
        });
        jPanel1.add(RestaurantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 40));

        LocationLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        LocationLabel.setForeground(new java.awt.Color(142, 142, 142));
        LocationLabel.setText("Location /");
        LocationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LocationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LocationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LocationLabelMouseExited(evt);
            }
        });
        jPanel1.add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 40));

        SigninLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        SigninLabel.setForeground(new java.awt.Color(142, 142, 142));
        SigninLabel.setText("Sign in /");
        SigninLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SigninLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SigninLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SigninLabelMouseExited(evt);
            }
        });
        jPanel1.add(SigninLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, -1, 40));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Gujarat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/Foodiezz.png"))); // NOI18N
        jPanel1.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        Address.setFont(new java.awt.Font("Narkisim", 0, 24)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Papyrus", 0, 24))); // NOI18N
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 460, 80));

        LabelBack.setOpaque(true);
        jPanel1.add(LabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1350, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(153, 153, 153));
        TypeLabel.setText("Cakes");
        Main_panel.add(TypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        S1.setBackground(new java.awt.Color(102, 102, 102));
        S1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 10, 50));

        S2.setBackground(new java.awt.Color(102, 102, 102));
        S2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 10, 50));

        S3.setBackground(new java.awt.Color(102, 102, 102));
        S3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 10, 450));

        S4.setBackground(new java.awt.Color(102, 102, 102));
        Main_panel.add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 1050, 10));

        CakesPanel.setBackground(new java.awt.Color(255, 255, 255));
        CakesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add1.setBackground(new java.awt.Color(9, 101, 0));
        Add1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("ADD");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        C1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        I1.setBackground(new java.awt.Color(255, 255, 255));
        I1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/1Pineapple Pastry 60.jpg"))); // NOI18N
        I1.setText("<html>Pineapple <br><font color = gray >Pastry</font><br><br><b>Rs.60");
        I1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I1.setIconTextGap(50);
        I1.setRequestFocusEnabled(false);
        I1.setVerifyInputWhenFocusTarget(false);
        I1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 220));

        IS1.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1050, 10));

        Add2.setBackground(new java.awt.Color(9, 101, 0));
        Add2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("ADD");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 80, 30));

        C2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 80, 30));

        I2.setBackground(new java.awt.Color(255, 255, 255));
        I2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/2chocolate-pastry 80.jpg"))); // NOI18N
        I2.setText("<html>Chocolate<br><font color = gray >Pastry</font><br><br><b>Rs.80");
        I2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I2.setIconTextGap(80);
        I2.setRequestFocusEnabled(false);
        I2.setVerifyInputWhenFocusTarget(false);
        I2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1050, 220));

        IS2.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1050, 10));

        Add3.setBackground(new java.awt.Color(9, 101, 0));
        Add3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("ADD");
        Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add3ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 80, 30));

        C3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 80, 30));

        I3.setBackground(new java.awt.Color(255, 255, 255));
        I3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/3Oreo Pastries 90.jpg"))); // NOI18N
        I3.setText("<html>Oreo<br><font color = gray >Pastry</font><br><br><b>Rs.90");
        I3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I3.setIconTextGap(80);
        I3.setRequestFocusEnabled(false);
        I3.setVerifyInputWhenFocusTarget(false);
        I3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1050, 220));

        IS3.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1050, 10));

        Add4.setBackground(new java.awt.Color(9, 101, 0));
        Add4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));
        Add4.setText("ADD");
        Add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add4ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 80, 30));

        C4.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 80, 30));

        I4.setBackground(new java.awt.Color(255, 255, 255));
        I4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/4Butterscotch Pastries 90.jpg"))); // NOI18N
        I4.setText("<html>Butterscotch<br><font color = gray >Pastry</font><br><br><b>Rs.90");
        I4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I4.setIconTextGap(80);
        I4.setRequestFocusEnabled(false);
        I4.setVerifyInputWhenFocusTarget(false);
        I4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1050, 220));

        IS4.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, 1050, 10));

        Add5.setBackground(new java.awt.Color(9, 101, 0));
        Add5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));
        Add5.setText("ADD");
        Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add5ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 940, 80, 30));

        C5.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 940, 80, 30));

        I5.setBackground(new java.awt.Color(255, 255, 255));
        I5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/5choco-chip-pastry 100.jpg"))); // NOI18N
        I5.setText("<html>Choco Chips<br><font color = gray >Pastry</font><br><br><b>Rs.100");
        I5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I5.setIconTextGap(80);
        I5.setRequestFocusEnabled(false);
        I5.setVerifyInputWhenFocusTarget(false);
        I5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 920, 1050, 220));

        IS5.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1140, 1050, 10));

        Add6.setBackground(new java.awt.Color(9, 101, 0));
        Add6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));
        Add6.setText("ADD");
        Add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add6ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1170, 80, 30));

        C6.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1170, 80, 30));

        I6.setBackground(new java.awt.Color(255, 255, 255));
        I6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/6Dutch Truffle Pastry 120.jpg"))); // NOI18N
        I6.setText("<html>Dutch Truffle<br><font color = gray >Pastry</font><br><br><b>Rs.120");
        I6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I6.setIconTextGap(80);
        I6.setRequestFocusEnabled(false);
        I6.setVerifyInputWhenFocusTarget(false);
        I6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1150, 1050, 220));

        IS6.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1370, 1050, 10));

        Add7.setBackground(new java.awt.Color(9, 101, 0));
        Add7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add7.setForeground(new java.awt.Color(255, 255, 255));
        Add7.setText("ADD");
        Add7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add7ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1400, 80, 30));

        C7.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1400, 80, 30));

        I7.setBackground(new java.awt.Color(255, 255, 255));
        I7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/7hazelnut-small---og466 300.jpg"))); // NOI18N
        I7.setText("<html>Hazelnut<br><font color = gray >Cakes</font><br><br><b>Rs.300");
        I7.setAutoscrolls(true);
        I7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I7.setIconTextGap(50);
        I7.setRequestFocusEnabled(false);
        I7.setVerifyInputWhenFocusTarget(false);
        I7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1380, 1050, 220));

        IS7.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1600, 1050, 10));

        Add8.setBackground(new java.awt.Color(9, 101, 0));
        Add8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add8.setForeground(new java.awt.Color(255, 255, 255));
        Add8.setText("ADD");
        Add8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add8ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1630, 80, 30));

        C8.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1630, 80, 30));

        I8.setBackground(new java.awt.Color(255, 255, 255));
        I8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/8black-forest-round-cake-small--og013 300.jpg"))); // NOI18N
        I8.setText("<html>Black Forest<br><font color = gray >Cakes</font><br><br><b>Rs.300");
        I8.setAutoscrolls(true);
        I8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I8.setIconTextGap(50);
        I8.setRequestFocusEnabled(false);
        I8.setVerifyInputWhenFocusTarget(false);
        I8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1610, 1050, 220));

        IS8.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1830, 1050, 10));

        Add9.setBackground(new java.awt.Color(9, 101, 0));
        Add9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add9.setForeground(new java.awt.Color(255, 255, 255));
        Add9.setText("ADD");
        Add9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add9ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1860, 80, 30));

        C9.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1860, 80, 30));

        I9.setBackground(new java.awt.Color(255, 255, 255));
        I9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/9black_forest_heart_cake_-_og769 350.jpg"))); // NOI18N
        I9.setText("<html>Black Forest Heart<br><font color = gray >Cakes</font><br><br><b>Rs.350");
        I9.setAutoscrolls(true);
        I9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I9.setIconTextGap(50);
        I9.setRequestFocusEnabled(false);
        I9.setVerifyInputWhenFocusTarget(false);
        I9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1840, 1050, 220));

        IS9.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2060, 1050, 10));

        Add10.setBackground(new java.awt.Color(9, 101, 0));
        Add10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add10.setForeground(new java.awt.Color(255, 255, 255));
        Add10.setText("ADD");
        Add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add10ActionPerformed(evt);
            }
        });
        CakesPanel.add(Add10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2090, 80, 30));

        C10.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        CakesPanel.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2090, 80, 30));

        I10.setBackground(new java.awt.Color(255, 255, 255));
        I10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Cake/10devils-delite_-_og021 350.jpg"))); // NOI18N
        I10.setText("<html>Devils Delite<br><font color = gray >Cakes</font><br><br><b>Rs.350");
        I10.setAutoscrolls(true);
        I10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I10.setIconTextGap(50);
        I10.setRequestFocusEnabled(false);
        I10.setVerifyInputWhenFocusTarget(false);
        I10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CakesPanel.add(I10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2070, 1050, 220));

        IS10.setBackground(new java.awt.Color(224, 224, 224));
        CakesPanel.add(IS10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2290, 1050, 10));

        Main_panel.add(CakesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 1050, 2270));

        SpecialPanel.setBackground(new java.awt.Color(255, 255, 255));
        SpecialPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add11.setBackground(new java.awt.Color(9, 101, 0));
        Add11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add11.setForeground(new java.awt.Color(255, 255, 255));
        Add11.setText("ADD");
        Add11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add11ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 30));

        C11.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 30));

        I11.setBackground(new java.awt.Color(255, 255, 255));
        I11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/1Wheat-Biscuit  20.jpg"))); // NOI18N
        I11.setText("<html>Wheat Biscuit<br><font color = gray >Cookies</font><br><br><b>Rs.20");
        I11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I11.setIconTextGap(40);
        I11.setRequestFocusEnabled(false);
        I11.setVerifyInputWhenFocusTarget(false);
        I11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 220));

        IS11.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1050, 10));

        Add12.setBackground(new java.awt.Color(9, 101, 0));
        Add12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add12.setForeground(new java.awt.Color(255, 255, 255));
        Add12.setText("ADD");
        Add12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add12ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 80, 30));

        C12.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 80, 30));

        I12.setBackground(new java.awt.Color(255, 255, 255));
        I12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/2Coconut-Cookies 30.jpg"))); // NOI18N
        I12.setText("<html>Coconut Cookies<br><font color = gray >Cookies</font><br><br><b>Rs.30");
        I12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I12.setIconTextGap(40);
        I12.setRequestFocusEnabled(false);
        I12.setVerifyInputWhenFocusTarget(false);
        I12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1050, 220));

        IS12.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1050, 10));

        Add13.setBackground(new java.awt.Color(9, 101, 0));
        Add13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add13.setForeground(new java.awt.Color(255, 255, 255));
        Add13.setText("ADD");
        Add13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add13ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 80, 30));

        C13.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 80, 30));

        I13.setBackground(new java.awt.Color(255, 255, 255));
        I13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/3Cream Horns 40.jpg"))); // NOI18N
        I13.setText("<html>Cream Horns<br><font color = gray >Cookies</font><br><br><b>Rs.40");
        I13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I13.setIconTextGap(40);
        I13.setRequestFocusEnabled(false);
        I13.setVerifyInputWhenFocusTarget(false);
        I13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1050, 220));

        IS13.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1050, 10));

        Add14.setBackground(new java.awt.Color(9, 101, 0));
        Add14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add14.setForeground(new java.awt.Color(255, 255, 255));
        Add14.setText("ADD");
        Add14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add14ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 700, 80, 30));

        C14.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 700, 80, 30));

        I14.setBackground(new java.awt.Color(255, 255, 255));
        I14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/4Sugar-free-Cookies 40.jpg"))); // NOI18N
        I14.setText("<html>Sugar Free Cookies<br><font color = gray >Cookies</font><br><br><b>Rs.40");
        I14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I14.setIconTextGap(40);
        I14.setRequestFocusEnabled(false);
        I14.setVerifyInputWhenFocusTarget(false);
        I14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1050, 220));

        IS14.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 900, 1050, 10));

        Add15.setBackground(new java.awt.Color(9, 101, 0));
        Add15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add15.setForeground(new java.awt.Color(255, 255, 255));
        Add15.setText("ADD");
        Add15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add15ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 930, 80, 30));

        C15.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 930, 80, 30));

        I15.setBackground(new java.awt.Color(255, 255, 255));
        I15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/5chocolate-cookies 50.jpg"))); // NOI18N
        I15.setText("<html>Chocolate Cookies<br><font color = gray >Cookies</font><br><br><b>Rs.50");
        I15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I15.setIconTextGap(40);
        I15.setRequestFocusEnabled(false);
        I15.setVerifyInputWhenFocusTarget(false);
        I15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, 1050, 220));

        IS15.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1130, 1050, 10));

        Add16.setBackground(new java.awt.Color(9, 101, 0));
        Add16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add16.setForeground(new java.awt.Color(255, 255, 255));
        Add16.setText("ADD");
        Add16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add16ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1160, 80, 30));

        C16.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1160, 80, 30));

        I16.setBackground(new java.awt.Color(255, 255, 255));
        I16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/6Macaron 60.jpg"))); // NOI18N
        I16.setText("<html>Macaron<br><font color = gray >Cookies</font><br><br><b>Rs.60");
        I16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I16.setIconTextGap(40);
        I16.setRequestFocusEnabled(false);
        I16.setVerifyInputWhenFocusTarget(false);
        I16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1140, 1050, 220));

        IS16.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1360, 1050, 10));

        Add17.setBackground(new java.awt.Color(9, 101, 0));
        Add17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add17.setForeground(new java.awt.Color(255, 255, 255));
        Add17.setText("ADD");
        Add17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add17ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1390, 80, 30));

        C17.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1390, 80, 30));

        I17.setBackground(new java.awt.Color(255, 255, 255));
        I17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/7Cinnamon Buns 70.jpg"))); // NOI18N
        I17.setText("<html>Cinnamon Buns (3 Pcs)<br><font color = gray >Cookies</font><br><br><b>Rs.70");
        I17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I17.setIconTextGap(40);
        I17.setRequestFocusEnabled(false);
        I17.setVerifyInputWhenFocusTarget(false);
        I17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1370, 1050, 220));

        IS17.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1590, 1050, 10));

        Add18.setBackground(new java.awt.Color(9, 101, 0));
        Add18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add18.setForeground(new java.awt.Color(255, 255, 255));
        Add18.setText("ADD");
        Add18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add18ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1620, 80, 30));

        C18.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1620, 80, 30));

        I18.setBackground(new java.awt.Color(255, 255, 255));
        I18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/8cinnamon.rolls.2 70.jpg"))); // NOI18N
        I18.setText("<html>Cinnamon Rolls (3 Pcs)<br><font color = gray >Cookies</font><br><br><b>Rs.70");
        I18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I18.setIconTextGap(40);
        I18.setRequestFocusEnabled(false);
        I18.setVerifyInputWhenFocusTarget(false);
        I18.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1600, 1050, 220));

        IS18.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1820, 1050, 10));

        Add19.setBackground(new java.awt.Color(9, 101, 0));
        Add19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add19.setForeground(new java.awt.Color(255, 255, 255));
        Add19.setText("ADD");
        Add19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add19ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add19, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1850, 80, 30));

        C19.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C19, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 1850, 80, 30));

        I19.setBackground(new java.awt.Color(255, 255, 255));
        I19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/9Chocolate Walnut Strudel 80.jpg"))); // NOI18N
        I19.setText("<html>Chocolate Walnut Strudel (1 Pcs)<br><font color = gray >Cookies</font><br><br><b>Rs.80");
        I19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I19.setIconTextGap(40);
        I19.setRequestFocusEnabled(false);
        I19.setVerifyInputWhenFocusTarget(false);
        I19.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1830, 1050, 220));

        IS19.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2050, 1050, 10));

        Add20.setBackground(new java.awt.Color(9, 101, 0));
        Add20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add20.setForeground(new java.awt.Color(255, 255, 255));
        Add20.setText("ADD");
        Add20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add20ActionPerformed(evt);
            }
        });
        SpecialPanel.add(Add20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2080, 80, 30));

        C20.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        SpecialPanel.add(C20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 2080, 80, 30));

        I20.setBackground(new java.awt.Color(255, 255, 255));
        I20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Breadliner(Ahmd)/Special/10Chocolate Eclair 100.jpeg"))); // NOI18N
        I20.setText("<html>Chocolate Eclair (1 Pcs)<br><font color = gray >Cookies</font><br><br><b>Rs.100");
        I20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I20.setIconTextGap(40);
        I20.setRequestFocusEnabled(false);
        I20.setVerifyInputWhenFocusTarget(false);
        I20.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        SpecialPanel.add(I20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2060, 1050, 220));

        IS20.setBackground(new java.awt.Color(224, 224, 224));
        SpecialPanel.add(IS20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2280, 1050, 10));

        Main_panel.add(SpecialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 1050, 2270));

        CakeLabel.setBackground(new java.awt.Color(255, 255, 255));
        CakeLabel.setFont(new java.awt.Font("Rockwell", 1, 28)); // NOI18N
        CakeLabel.setForeground(new java.awt.Color(153, 153, 153));
        CakeLabel.setText("Cakes");
        CakeLabel.setOpaque(true);
        CakeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CakeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CakeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CakeLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CakeLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CakeLabelMouseReleased(evt);
            }
        });
        Main_panel.add(CakeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, -1));

        SpecialLabel.setBackground(new java.awt.Color(255, 255, 255));
        SpecialLabel.setFont(new java.awt.Font("Rockwell", 1, 28)); // NOI18N
        SpecialLabel.setForeground(new java.awt.Color(153, 153, 153));
        SpecialLabel.setText("Special");
        SpecialLabel.setOpaque(true);
        SpecialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SpecialLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SpecialLabelMousePressed(evt);
            }
        });
        Main_panel.add(SpecialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 190, -1));

        KB_Label.setBackground(new java.awt.Color(0, 15, 40));
        KB_Label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        KB_Label.setForeground(new java.awt.Color(255, 255, 255));
        KB_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restaurants/Ahemdabad/Breadliner.jpeg"))); // NOI18N
        KB_Label.setText("<html><font color = 'white' size = 15>Breadliner</font><br><t><font color = gray>Ahemdabad</br><br>Bakery Products</font></br><br><br><br>4.9 / 5 <t> <t> <t><t> <t> <t> <t> <t><t> <t><t><t><t><t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>   <font color = white><t>    Rs.180</font><t>  <t>  <t> <t> <t>  <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>    <t> <t>  <t>  <t>   <t>  <t>  <t>  <t>  <t> <font color = white> 30 Minutes </font><br><font size=5 color = gray> 820+ Ratings<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t> <t>  <t> <t> <t>Cost For Two<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>  <t>    Delivery Time</font></br>"); // NOI18N
        KB_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new java.awt.Color(0, 15, 40)));
        KB_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KB_Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        KB_Label.setIconTextGap(20);
        KB_Label.setOpaque(true);
        KB_Label.setRequestFocusEnabled(false);
        KB_Label.setVerifyInputWhenFocusTarget(false);
        KB_Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(KB_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 280));

        jScrollPane1.setViewportView(Main_panel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1350, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setLocationRelativeTo(null);
        try{
    Class.forName("java.sql.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
    Statement stat = con.createStatement();
    String query = "Select * from Location;";
    rs = stat.executeQuery(query);
    while(rs.next()){
        String pn = rs.getString("Plot_no");
        String ar = rs.getString("Area");
        String land = rs.getString("Landmark");
        String pin = rs.getString("Pincode");
        String ct = rs.getString("City");
        String resi = rs.getString("Residence");
        Address.setText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
        Address.setToolTipText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
                
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, "Error in Adress",null,-2);
}
        
C1.setVisible(false);
C2.setVisible(false);
C3.setVisible(false);
C4.setVisible(false);
C5.setVisible(false);
C6.setVisible(false);
C7.setVisible(false);
C8.setVisible(false);
C9.setVisible(false);
C10.setVisible(false);
C11.setVisible(false);
C12.setVisible(false);
C13.setVisible(false);
C14.setVisible(false);
C15.setVisible(false);
C16.setVisible(false);
C17.setVisible(false);
C18.setVisible(false);
C19.setVisible(false);
C20.setVisible(false);


CakesPanel.setVisible(true);
SpecialPanel.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void CakeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CakeLabelMouseEntered
CakeLabel.setBackground(Color.GRAY);
CakeLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_CakeLabelMouseEntered

    private void CakeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CakeLabelMouseExited
CakeLabel.setBackground(Color.WHITE);
CakeLabel.setForeground(Color.GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_CakeLabelMouseExited

    private void SpecialLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseEntered
SpecialLabel.setBackground(Color.GRAY);
SpecialLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseEntered

    private void SpecialLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseExited
SpecialLabel.setBackground(Color.WHITE);
SpecialLabel.setForeground(Color.GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseExited

    private void SpecialLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseClicked
TypeLabel.setText("Special");
SpecialPanel.setVisible(true);
CakesPanel.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseClicked

    private void CakeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CakeLabelMouseClicked
TypeLabel.setText("Packs");
CakesPanel.setVisible(true);
SpecialPanel.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_CakeLabelMouseClicked

    private void CakeLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CakeLabelMousePressed
CakeLabel.setBackground(Color.DARK_GRAY);
CakeLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_CakeLabelMousePressed

    private void CakeLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CakeLabelMouseReleased
CakeLabel.setBackground(Color.GRAY);
CakeLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_CakeLabelMouseReleased

    private void SpecialLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMousePressed
SpecialLabel.setBackground(Color.DARK_GRAY);
SpecialLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMousePressed

    private void SpecialLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialLabelMouseReleased
SpecialLabel.setBackground(Color.GRAY);
SpecialLabel.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialLabelMouseReleased

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
C1.setVisible(true);
Add1.setVisible(false);
C1.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed

    private void RestaurantLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = blue>Go back to Restaurants(Ahemdabad) Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            Project_Frames._4_Main_Order_Gujarat_Ahemdabad.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseClicked

    private void RestaurantLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseEntered
        RestaurantLabel.setText("<html><u>Restaurant(Ahemdabad)</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseEntered

    private void RestaurantLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseExited
        RestaurantLabel.setText("Restaurant(Ahemdabad) /");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseExited

    private void LocationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = Green>Go back to Location Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _3_Location.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseClicked

    private void LocationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseEntered
        LocationLabel.setText("<html><u>Location</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseEntered

    private void LocationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseExited
        LocationLabel.setText("Location /");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseExited

    private void SigninLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = orange>Go back to Sign in Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _2_Login.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseClicked

    private void SigninLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseEntered
        SigninLabel.setText("<html><u>Sign in</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseEntered

    private void SigninLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseExited
        SigninLabel.setText("Sign in /");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseExited

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
int c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20;
    
    c1 = (int) C1.getValue();
    c2 = (int) C2.getValue();
    c3 = (int) C3.getValue();
    c4 = (int) C4.getValue();
    c5 = (int) C5.getValue();
    c6 = (int) C6.getValue();
    c7 = (int) C7.getValue();
    c8 = (int) C8.getValue();
    c9 = (int) C9.getValue();
    c10 = (int) C10.getValue();
    c11 = (int) C11.getValue();
    c12 = (int) C12.getValue();
    c13 = (int) C13.getValue();
    c14 = (int) C14.getValue();
    c15 = (int) C15.getValue();
    c16 = (int) C16.getValue();
    c17 = (int) C17.getValue();
    c18 = (int) C18.getValue();
    c19 = (int) C19.getValue();
    c20 = (int) C20.getValue();
      
    if(c1 > 0 || c2 > 0 || c3 > 0 || c4 > 0 || c5 > 0 || c6 > 0 || c7 > 0 || c8 > 0 || c9 > 0 || c10 > 0 || c11 > 0 || c12 > 0 || c13 > 0 || c14 > 0 || c15 > 0 || c16 > 0 || c17 > 0 || c18 > 0 || c19 > 0 || c20 > 0 ){
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
            stat = con.createStatement();
            String query1 = "Delete from cart;";
            stat.executeUpdate(query1);

            if (c1 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Pineapple Pastry', 60," + c1 + ");";
                stat.executeUpdate(query);
            }if (c2 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Chocolate Pastry', 80," + c2 + ");";
                stat.executeUpdate(query);
            }if (c3 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Oreo Pastry', 90," + c3 + ");";
                stat.executeUpdate(query);
            }if (c4 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Butterscotch Pastry', 90," + c4 + ");";
                stat.executeUpdate(query);
            }if (c5 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Choco Chips Pastry', 100," + c5 + ");";
                stat.executeUpdate(query);
            }if (c6 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Dutch Truffle Pastry', 120," + c6 + ");";
                stat.executeUpdate(query);
            }if (c7 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Hazelnut Cake (500g)', 300," + c7 + ");";
                stat.executeUpdate(query);
            }if (c8 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Black Forest Cake (500g)', 300," + c8 + ");";
                stat.executeUpdate(query);
            }if (c9 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Black Forest Heart Cake (500g)', 350," + c9 + ");";
                stat.executeUpdate(query);
            }if (c10 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Devils Delite Cake (500g)', 350," + c10 + ");";
                stat.executeUpdate(query);
            }if (c11 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Wheat Biscuit (5 Pcs)', 20," + c11 + ");";
                stat.executeUpdate(query);
            }if (c12 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Coconut Cookies (5 Pcs)', 30," + c12 + ");";
                stat.executeUpdate(query);
            }if (c13 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Cream Horns (2 Pcs)', 40," + c13 + ");";
                stat.executeUpdate(query);
            }if (c14 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Sugar Free Cookies (5 Pcs)', 40," + c14 + ");";
                stat.executeUpdate(query);
            }if (c15 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Chocolate Cookies (5 Pcs)', 50," + c15 + ");";
                stat.executeUpdate(query);
            }if (c16 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Macaron (3 Pcs)', 60," + c16 + ");";
                stat.executeUpdate(query);
            }if (c17 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Cinnamon Buns (3 Pcs)', 70," + c17 + ");";
                stat.executeUpdate(query);
            }if (c18 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Cinnamon Rolls (3 Pcs)', 70," + c18 + ");";
                stat.executeUpdate(query);
            }if (c19 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Chocolate Walnut Strudel (1 Pcs)', 80," + c19 + ");";
                stat.executeUpdate(query);
            }if (c20 > 0) {
                String query = "Insert into cart values ('Breadliner', 'Chocolate Eclair (1 Pcs)', 100," + c20 + ");";
                stat.executeUpdate(query);
            } 
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error in Cart Button", null, 2);
        }
    }

    int Ans = JOptionPane.showConfirmDialog(this, "<html><font color = green size = 15 face = rockwell>Do you want to add Items to Cart?", null, 0, -1);
    if (Ans == JOptionPane.YES_OPTION) {
        Restaurants.Cart.main(null);
            this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBtnActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
C2.setVisible(true);
Add2.setVisible(false);
C2.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add3ActionPerformed
C3.setVisible(true);
Add3.setVisible(false);
C3.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add3ActionPerformed

    private void Add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add4ActionPerformed
C4.setVisible(true);
Add4.setVisible(false);
C4.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add4ActionPerformed

    private void Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add5ActionPerformed
C5.setVisible(true);
Add5.setVisible(false);
C5.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add5ActionPerformed

    private void Add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add6ActionPerformed
C6.setVisible(true);
Add6.setVisible(false);
C6.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add6ActionPerformed

    private void Add7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add7ActionPerformed
C7.setVisible(true);
Add7.setVisible(false);
C7.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add7ActionPerformed

    private void Add8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add8ActionPerformed
C8.setVisible(true);
Add8.setVisible(false);
C8.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add8ActionPerformed

    private void Add9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add9ActionPerformed
C9.setVisible(true);
Add9.setVisible(false);
C9.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add9ActionPerformed

    private void Add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add10ActionPerformed
C10.setVisible(true);
Add10.setVisible(false);
C10.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add10ActionPerformed

    private void Add19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add19ActionPerformed
C19.setVisible(true);
Add19.setVisible(false);
C19.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add19ActionPerformed

    private void Add20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add20ActionPerformed
C20.setVisible(true);
Add20.setVisible(false);
C20.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add20ActionPerformed

    private void Add11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add11ActionPerformed
C11.setVisible(true);
Add11.setVisible(false);
C11.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add11ActionPerformed

    private void Add12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add12ActionPerformed
C12.setVisible(true);
Add12.setVisible(false);
C12.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add12ActionPerformed

    private void Add13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add13ActionPerformed
C13.setVisible(true);
Add13.setVisible(false);
C13.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add13ActionPerformed

    private void Add14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add14ActionPerformed
C14.setVisible(true);
Add14.setVisible(false);
C14.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add14ActionPerformed

    private void Add15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add15ActionPerformed
C15.setVisible(true);
Add15.setVisible(false);
C15.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add15ActionPerformed

    private void Add16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add16ActionPerformed
C16.setVisible(true);
Add16.setVisible(false);
C16.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add16ActionPerformed

    private void Add17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add17ActionPerformed
C17.setVisible(true);
Add17.setVisible(false);
C17.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add17ActionPerformed

    private void Add18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add18ActionPerformed
C18.setVisible(true);
Add18.setVisible(false);
C18.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Breadliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Breadliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Breadliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahemdabad_Breadliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahemdabad_Breadliner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add10;
    private javax.swing.JButton Add11;
    private javax.swing.JButton Add12;
    private javax.swing.JButton Add13;
    private javax.swing.JButton Add14;
    private javax.swing.JButton Add15;
    private javax.swing.JButton Add16;
    private javax.swing.JButton Add17;
    private javax.swing.JButton Add18;
    private javax.swing.JButton Add19;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Add20;
    private javax.swing.JButton Add3;
    private javax.swing.JButton Add4;
    private javax.swing.JButton Add5;
    private javax.swing.JButton Add6;
    private javax.swing.JButton Add7;
    private javax.swing.JButton Add8;
    private javax.swing.JButton Add9;
    private javax.swing.JLabel Address;
    private javax.swing.JSpinner C1;
    private javax.swing.JSpinner C10;
    private javax.swing.JSpinner C11;
    private javax.swing.JSpinner C12;
    private javax.swing.JSpinner C13;
    private javax.swing.JSpinner C14;
    private javax.swing.JSpinner C15;
    private javax.swing.JSpinner C16;
    private javax.swing.JSpinner C17;
    private javax.swing.JSpinner C18;
    private javax.swing.JSpinner C19;
    private javax.swing.JSpinner C2;
    private javax.swing.JSpinner C20;
    private javax.swing.JSpinner C3;
    private javax.swing.JSpinner C4;
    private javax.swing.JSpinner C5;
    private javax.swing.JSpinner C6;
    private javax.swing.JSpinner C7;
    private javax.swing.JSpinner C8;
    private javax.swing.JSpinner C9;
    private javax.swing.JLabel CakeLabel;
    private javax.swing.JPanel CakesPanel;
    private javax.swing.JButton CartBtn;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I10;
    private javax.swing.JLabel I11;
    private javax.swing.JLabel I12;
    private javax.swing.JLabel I13;
    private javax.swing.JLabel I14;
    private javax.swing.JLabel I15;
    private javax.swing.JLabel I16;
    private javax.swing.JLabel I17;
    private javax.swing.JLabel I18;
    private javax.swing.JLabel I19;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I20;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JLabel I5;
    private javax.swing.JLabel I6;
    private javax.swing.JLabel I7;
    private javax.swing.JLabel I8;
    private javax.swing.JLabel I9;
    private javax.swing.JSeparator IS1;
    private javax.swing.JSeparator IS10;
    private javax.swing.JSeparator IS11;
    private javax.swing.JSeparator IS12;
    private javax.swing.JSeparator IS13;
    private javax.swing.JSeparator IS14;
    private javax.swing.JSeparator IS15;
    private javax.swing.JSeparator IS16;
    private javax.swing.JSeparator IS17;
    private javax.swing.JSeparator IS18;
    private javax.swing.JSeparator IS19;
    private javax.swing.JSeparator IS2;
    private javax.swing.JSeparator IS20;
    private javax.swing.JSeparator IS3;
    private javax.swing.JSeparator IS4;
    private javax.swing.JSeparator IS5;
    private javax.swing.JSeparator IS6;
    private javax.swing.JSeparator IS7;
    private javax.swing.JSeparator IS8;
    private javax.swing.JSeparator IS9;
    private javax.swing.JLabel KBLabel;
    private javax.swing.JLabel KB_Label;
    private javax.swing.JLabel LabelBack;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JLabel RestaurantLabel;
    private javax.swing.JSeparator S1;
    private javax.swing.JSeparator S2;
    private javax.swing.JSeparator S3;
    private javax.swing.JSeparator S4;
    private javax.swing.JLabel SigninLabel;
    private javax.swing.JLabel SpecialLabel;
    private javax.swing.JPanel SpecialPanel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
