/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurants;

import Project_Frames._2_Login;
import Project_Frames._3_Location;
import Project_Frames._4_Main_Order_Gujarat_Surat;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Surat_Laziz_Pizza extends javax.swing.JFrame {
Connection con;
ResultSet rs;
Statement stat;
    /**
     * Creates new form Gangour  
     */
    public Surat_Laziz_Pizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CartBtn = new javax.swing.JButton();
        PALabel = new javax.swing.JLabel();
        RestaurantLabel = new javax.swing.JLabel();
        LocationLabel = new javax.swing.JLabel();
        SigninLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        LabelBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Main_panel = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        S1 = new javax.swing.JSeparator();
        S2 = new javax.swing.JSeparator();
        S3 = new javax.swing.JSeparator();
        S4 = new javax.swing.JSeparator();
        SDScroll = new javax.swing.JScrollPane();
        SDPanel = new javax.swing.JPanel();
        I18 = new javax.swing.JLabel();
        Add18 = new javax.swing.JButton();
        C18 = new javax.swing.JSpinner();
        IS18 = new javax.swing.JSeparator();
        I19 = new javax.swing.JLabel();
        Add19 = new javax.swing.JButton();
        C19 = new javax.swing.JSpinner();
        IS19 = new javax.swing.JSeparator();
        I20 = new javax.swing.JLabel();
        Add20 = new javax.swing.JButton();
        C20 = new javax.swing.JSpinner();
        IS20 = new javax.swing.JSeparator();
        I21 = new javax.swing.JLabel();
        Add21 = new javax.swing.JButton();
        IS21 = new javax.swing.JSeparator();
        C21 = new javax.swing.JSpinner();
        I22 = new javax.swing.JLabel();
        Add22 = new javax.swing.JButton();
        C22 = new javax.swing.JSpinner();
        IS22 = new javax.swing.JSeparator();
        Add1 = new javax.swing.JButton();
        C1 = new javax.swing.JSpinner();
        I1 = new javax.swing.JLabel();
        IS1 = new javax.swing.JSeparator();
        Add2 = new javax.swing.JButton();
        C2 = new javax.swing.JSpinner();
        I2 = new javax.swing.JLabel();
        IS2 = new javax.swing.JSeparator();
        Add3 = new javax.swing.JButton();
        C3 = new javax.swing.JSpinner();
        I3 = new javax.swing.JLabel();
        IS3 = new javax.swing.JSeparator();
        Add4 = new javax.swing.JButton();
        C4 = new javax.swing.JSpinner();
        I4 = new javax.swing.JLabel();
        IS4 = new javax.swing.JSeparator();
        Add5 = new javax.swing.JButton();
        C5 = new javax.swing.JSpinner();
        I5 = new javax.swing.JLabel();
        IS5 = new javax.swing.JSeparator();
        Add6 = new javax.swing.JButton();
        C6 = new javax.swing.JSpinner();
        I6 = new javax.swing.JLabel();
        IS6 = new javax.swing.JSeparator();
        Add11 = new javax.swing.JButton();
        C11 = new javax.swing.JSpinner();
        I11 = new javax.swing.JLabel();
        Add12 = new javax.swing.JButton();
        C12 = new javax.swing.JSpinner();
        I12 = new javax.swing.JLabel();
        IS16 = new javax.swing.JSeparator();
        Add13 = new javax.swing.JButton();
        C13 = new javax.swing.JSpinner();
        I13 = new javax.swing.JLabel();
        IS12 = new javax.swing.JSeparator();
        Add14 = new javax.swing.JButton();
        C14 = new javax.swing.JSpinner();
        I14 = new javax.swing.JLabel();
        IS13 = new javax.swing.JSeparator();
        Add15 = new javax.swing.JButton();
        C15 = new javax.swing.JSpinner();
        I15 = new javax.swing.JLabel();
        IS14 = new javax.swing.JSeparator();
        Add16 = new javax.swing.JButton();
        C16 = new javax.swing.JSpinner();
        I16 = new javax.swing.JLabel();
        IS15 = new javax.swing.JSeparator();
        Add17 = new javax.swing.JButton();
        C17 = new javax.swing.JSpinner();
        I17 = new javax.swing.JLabel();
        KB_Label = new javax.swing.JLabel();
        S5 = new javax.swing.JSeparator();
        TypeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laziz Pizza");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartBtn.setBackground(new java.awt.Color(0, 153, 204));
        CartBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        CartBtn.setText("Cart");
        CartBtn.setRequestFocusEnabled(false);
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 140, -1));

        PALabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        PALabel.setForeground(new java.awt.Color(51, 51, 51));
        PALabel.setText("Laziz Pizza");
        jPanel1.add(PALabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 40));

        RestaurantLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        RestaurantLabel.setForeground(new java.awt.Color(142, 142, 142));
        RestaurantLabel.setText("Restaurant(Surat) /");
        RestaurantLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestaurantLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestaurantLabelMouseExited(evt);
            }
        });
        jPanel1.add(RestaurantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 40));

        LocationLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        LocationLabel.setForeground(new java.awt.Color(142, 142, 142));
        LocationLabel.setText("Location /");
        LocationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LocationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LocationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LocationLabelMouseExited(evt);
            }
        });
        jPanel1.add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 40));

        SigninLabel.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        SigninLabel.setForeground(new java.awt.Color(142, 142, 142));
        SigninLabel.setText("Sign in /");
        SigninLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SigninLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SigninLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SigninLabelMouseExited(evt);
            }
        });
        jPanel1.add(SigninLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, -1, 40));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Gujarat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/Foodiezz.png"))); // NOI18N
        jPanel1.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        Address.setFont(new java.awt.Font("Narkisim", 0, 24)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Papyrus", 0, 24))); // NOI18N
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 460, 80));

        LabelBack.setOpaque(true);
        jPanel1.add(LabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1350, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(102, 102, 102));
        TypeLabel.setText("Veg. Pizza");
        Main_panel.add(TypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        S1.setBackground(new java.awt.Color(102, 102, 102));
        S1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 10, 50));

        S2.setBackground(new java.awt.Color(102, 102, 102));
        S2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 10, 50));

        S3.setBackground(new java.awt.Color(102, 102, 102));
        S3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main_panel.add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 10, 870));

        S4.setBackground(new java.awt.Color(51, 51, 51));
        Main_panel.add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 1050, 10));

        SDScroll.setBackground(new java.awt.Color(255, 255, 255));
        SDScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html>Soft Drinks<br>(Rs.80)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Rockwell", 1, 24), new java.awt.Color(153, 153, 153))); // NOI18N
        SDScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        SDPanel.setBackground(new java.awt.Color(255, 255, 255));
        SDPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        I18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Bev/coca zero.jpg"))); // NOI18N
        SDPanel.add(I18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        Add18.setBackground(new java.awt.Color(9, 101, 0));
        Add18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add18.setForeground(new java.awt.Color(255, 255, 255));
        Add18.setText("ADD");
        Add18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add18ActionPerformed(evt);
            }
        });
        SDPanel.add(Add18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, 30));

        C18.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SDPanel.add(C18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, 30));
        SDPanel.add(IS18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 10));

        I19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Bev/coke.png"))); // NOI18N
        SDPanel.add(I19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 200));

        Add19.setBackground(new java.awt.Color(9, 101, 0));
        Add19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add19.setForeground(new java.awt.Color(255, 255, 255));
        Add19.setText("ADD");
        Add19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add19ActionPerformed(evt);
            }
        });
        SDPanel.add(Add19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 80, 30));

        C19.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SDPanel.add(C19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 80, 30));
        SDPanel.add(IS19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 200, 10));

        I20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Bev/fanta.png"))); // NOI18N
        SDPanel.add(I20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 200, 200));

        Add20.setBackground(new java.awt.Color(9, 101, 0));
        Add20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add20.setForeground(new java.awt.Color(255, 255, 255));
        Add20.setText("ADD");
        Add20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add20ActionPerformed(evt);
            }
        });
        SDPanel.add(Add20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 80, 30));

        C20.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SDPanel.add(C20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 80, 30));
        SDPanel.add(IS20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 200, 10));

        I21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Bev/sprite.png"))); // NOI18N
        SDPanel.add(I21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 200, 200));

        Add21.setBackground(new java.awt.Color(9, 101, 0));
        Add21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add21.setForeground(new java.awt.Color(255, 255, 255));
        Add21.setText("ADD");
        Add21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add21ActionPerformed(evt);
            }
        });
        SDPanel.add(Add21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, 80, 30));
        SDPanel.add(IS21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1060, 200, 10));

        C21.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SDPanel.add(C21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, 80, 30));

        I22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Bev/thumsup.png"))); // NOI18N
        SDPanel.add(I22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1080, 200, 200));

        Add22.setBackground(new java.awt.Color(9, 101, 0));
        Add22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add22.setForeground(new java.awt.Color(255, 255, 255));
        Add22.setText("ADD");
        Add22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add22ActionPerformed(evt);
            }
        });
        SDPanel.add(Add22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1290, 80, 30));

        C22.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SDPanel.add(C22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1290, 80, 30));
        SDPanel.add(IS22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1330, 200, 10));

        SDScroll.setViewportView(SDPanel);

        Main_panel.add(SDScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 207, 600));

        Add1.setBackground(new java.awt.Color(9, 101, 0));
        Add1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("ADD");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        Main_panel.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 370, 80, 30));

        C1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 370, 80, 30));

        I1.setBackground(new java.awt.Color(255, 255, 255));
        I1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/1 Margherit 150.jpg"))); // NOI18N
        I1.setText("<html>Margherit<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.150");
        I1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I1.setIconTextGap(15);
        I1.setRequestFocusEnabled(false);
        I1.setVerifyInputWhenFocusTarget(false);
        I1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 1050, 220));

        IS1.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 1050, 10));

        Add2.setBackground(new java.awt.Color(9, 101, 0));
        Add2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("ADD");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        Main_panel.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, 80, 30));

        C2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, 80, 30));

        I2.setBackground(new java.awt.Color(255, 255, 255));
        I2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/2 Fresh_Veggie 180.jpg"))); // NOI18N
        I2.setText("<html>Fresh Veggies<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.180");
        I2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I2.setIconTextGap(15);
        I2.setRequestFocusEnabled(false);
        I2.setVerifyInputWhenFocusTarget(false);
        I2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 1050, 220));

        IS2.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 820, 1050, 10));

        Add3.setBackground(new java.awt.Color(9, 101, 0));
        Add3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("ADD");
        Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add3ActionPerformed(evt);
            }
        });
        Main_panel.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 850, 80, 30));

        C3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 850, 80, 30));

        I3.setBackground(new java.awt.Color(255, 255, 255));
        I3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/3 Digital_Veggie_Paradise 200.jpg"))); // NOI18N
        I3.setText("<html>Digital Veggie Paradise<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.200");
        I3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I3.setIconTextGap(15);
        I3.setRequestFocusEnabled(false);
        I3.setVerifyInputWhenFocusTarget(false);
        I3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 830, 1050, 220));

        IS3.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1050, 1050, 10));

        Add4.setBackground(new java.awt.Color(9, 101, 0));
        Add4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));
        Add4.setText("ADD");
        Add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add4ActionPerformed(evt);
            }
        });
        Main_panel.add(Add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 1090, 80, 30));

        C4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 1090, 80, 30));

        I4.setBackground(new java.awt.Color(255, 255, 255));
        I4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/4 Paneer_Makhni 210.jpg"))); // NOI18N
        I4.setText("<html>Paneer Makhni<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.210");
        I4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I4.setIconTextGap(15);
        I4.setRequestFocusEnabled(false);
        I4.setVerifyInputWhenFocusTarget(false);
        I4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1070, 1050, 220));

        IS4.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1300, 1050, 10));

        Add5.setBackground(new java.awt.Color(9, 101, 0));
        Add5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));
        Add5.setText("ADD");
        Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add5ActionPerformed(evt);
            }
        });
        Main_panel.add(Add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 1340, 80, 30));

        C5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 1340, 80, 30));

        I5.setBackground(new java.awt.Color(255, 255, 255));
        I5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/5 Deluxe_Veggie 230.jpg"))); // NOI18N
        I5.setText("<html>Dulex Veggie<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.230");
        I5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I5.setIconTextGap(15);
        I5.setRequestFocusEnabled(false);
        I5.setVerifyInputWhenFocusTarget(false);
        I5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1320, 1050, 220));

        IS5.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1550, 1050, 10));

        Add6.setBackground(new java.awt.Color(9, 101, 0));
        Add6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));
        Add6.setText("ADD");
        Add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add6ActionPerformed(evt);
            }
        });
        Main_panel.add(Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 1590, 80, 30));

        C6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 1590, 80, 30));

        I6.setBackground(new java.awt.Color(255, 255, 255));
        I6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/6 Peppy_Paneer 250.jpg"))); // NOI18N
        I6.setText("<html>Peppy Paneer<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.250");
        I6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I6.setIconTextGap(15);
        I6.setRequestFocusEnabled(false);
        I6.setVerifyInputWhenFocusTarget(false);
        I6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1570, 1050, 220));

        IS6.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1800, 1050, 10));

        Add11.setBackground(new java.awt.Color(9, 101, 0));
        Add11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add11.setForeground(new java.awt.Color(255, 255, 255));
        Add11.setText("ADD");
        Add11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add11ActionPerformed(evt);
            }
        });
        Main_panel.add(Add11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 1840, 80, 30));

        C11.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 1840, 80, 30));

        I11.setBackground(new java.awt.Color(255, 255, 255));
        I11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/7 Farmhouse 260.jpg"))); // NOI18N
        I11.setText("<html>Farmhouse<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.260");
        I11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I11.setIconTextGap(15);
        I11.setRequestFocusEnabled(false);
        I11.setVerifyInputWhenFocusTarget(false);
        I11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1820, 1050, 220));

        Add12.setBackground(new java.awt.Color(9, 101, 0));
        Add12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add12.setForeground(new java.awt.Color(255, 255, 255));
        Add12.setText("ADD");
        Add12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add12ActionPerformed(evt);
            }
        });
        Main_panel.add(Add12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2080, 80, 30));

        C12.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 2080, 80, 30));

        I12.setBackground(new java.awt.Color(255, 255, 255));
        I12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/8 Mexican_Green_Wave 280.jpg"))); // NOI18N
        I12.setText("<html>Mexican Green Wave<br><font color = gray >Veg. Pizza</font><br><br><b>Rs.280");
        I12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I12.setIconTextGap(15);
        I12.setRequestFocusEnabled(false);
        I12.setVerifyInputWhenFocusTarget(false);
        I12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2060, 1050, 220));

        IS16.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2050, 1050, 10));

        Add13.setBackground(new java.awt.Color(9, 101, 0));
        Add13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add13.setForeground(new java.awt.Color(255, 255, 255));
        Add13.setText("ADD");
        Add13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add13ActionPerformed(evt);
            }
        });
        Main_panel.add(Add13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2410, 80, 30));

        C13.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2410, 80, 30));

        I13.setBackground(new java.awt.Color(255, 255, 255));
        I13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Non/1 Pepper_Barbeque 120.jpg"))); // NOI18N
        I13.setText("<html>Pepper Barbeque<br><font color = gray >Non Veg. Pizza</font><br><br><b>Rs.120");
        I13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I13.setIconTextGap(15);
        I13.setRequestFocusEnabled(false);
        I13.setVerifyInputWhenFocusTarget(false);
        I13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2390, 1050, 220));

        IS12.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2610, 1050, 10));

        Add14.setBackground(new java.awt.Color(9, 101, 0));
        Add14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add14.setForeground(new java.awt.Color(255, 255, 255));
        Add14.setText("ADD");
        Add14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add14ActionPerformed(evt);
            }
        });
        Main_panel.add(Add14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2650, 80, 30));

        C14.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2650, 80, 30));

        I14.setBackground(new java.awt.Color(255, 255, 255));
        I14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Non/2 Chicken_Golden_Delight 150.jpg"))); // NOI18N
        I14.setText("<html>Golden Chicken Delight<br><font color = gray >Non Veg. Pizza</font><br><br><b>Rs.150");
        I14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I14.setIconTextGap(15);
        I14.setRequestFocusEnabled(false);
        I14.setVerifyInputWhenFocusTarget(false);
        I14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2630, 1050, 220));

        IS13.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2860, 1050, 10));

        Add15.setBackground(new java.awt.Color(9, 101, 0));
        Add15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add15.setForeground(new java.awt.Color(255, 255, 255));
        Add15.setText("ADD");
        Add15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add15ActionPerformed(evt);
            }
        });
        Main_panel.add(Add15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2890, 80, 30));

        C15.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2890, 80, 30));

        I15.setBackground(new java.awt.Color(255, 255, 255));
        I15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Non/3 Dominator 180.jpg"))); // NOI18N
        I15.setText("<html>Dominator<br><font color = gray >Non Veg. Pizza</font><br><br><b>Rs.180");
        I15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I15.setIconTextGap(15);
        I15.setRequestFocusEnabled(false);
        I15.setVerifyInputWhenFocusTarget(false);
        I15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2870, 1050, 220));

        IS14.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 3090, 1050, 10));

        Add16.setBackground(new java.awt.Color(9, 101, 0));
        Add16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add16.setForeground(new java.awt.Color(255, 255, 255));
        Add16.setText("ADD");
        Add16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add16ActionPerformed(evt);
            }
        });
        Main_panel.add(Add16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 3130, 80, 30));

        C16.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 3130, 80, 30));

        I16.setBackground(new java.awt.Color(255, 255, 255));
        I16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Non/4 chunky-chicken 210.png"))); // NOI18N
        I16.setText("<html>Chunky Chicken<br><font color = gray >Non Veg. Pizza</font><br><br><b>Rs.210");
        I16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I16.setIconTextGap(50);
        I16.setRequestFocusEnabled(false);
        I16.setVerifyInputWhenFocusTarget(false);
        I16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 3110, 1050, 220));

        IS15.setBackground(new java.awt.Color(224, 224, 224));
        Main_panel.add(IS15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 3340, 1050, 10));

        Add17.setBackground(new java.awt.Color(9, 101, 0));
        Add17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add17.setForeground(new java.awt.Color(255, 255, 255));
        Add17.setText("ADD");
        Add17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add17ActionPerformed(evt);
            }
        });
        Main_panel.add(Add17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 3380, 80, 30));

        C17.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Main_panel.add(C17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 3380, 80, 30));

        I17.setBackground(new java.awt.Color(255, 255, 255));
        I17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        I17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Food/Laziz Pizza (Surat)/Non/5 Non-Veg_Supreme 230.jpg"))); // NOI18N
        I17.setText("<html>Non Veg. Supreme<br><font color = gray >Non Veg. Pizza</font><br><br><b>Rs.230");
        I17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        I17.setIconTextGap(15);
        I17.setRequestFocusEnabled(false);
        I17.setVerifyInputWhenFocusTarget(false);
        I17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(I17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 3360, 1050, 220));

        KB_Label.setBackground(new java.awt.Color(0, 15, 40));
        KB_Label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        KB_Label.setForeground(new java.awt.Color(255, 255, 255));
        KB_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restaurants/Surat/Laziz Pizza.jpg"))); // NOI18N
        KB_Label.setText("<html><font color = 'white' size = 15>Laziz Pizza</font><br><t><font color = gray>Surat</br><br>Pizzas</font></br><br><br><br>4.3 / 5 <t> <t> <t><t> <t> <t> <t> <t><t> <t><t><t><t><t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>   <font color = white><t>    Rs.200</font><t>  <t>  <t> <t> <t>  <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t> <t>  <t>    <t> <t>  <t>  <t>   <t>  <t>  <t>  <t>  <t> <font color = white>  25 Minutes </font><br><font size=5 color = gray> 600+ Ratings<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t> <t>  <t> <t> <t>Cost For Two<t> <t>  <t>  <t> <t>  <t> <t>  <t>  <t>  <t>  <t>  <t>  <t>    Delivery Time</font></br>"); // NOI18N
        KB_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new java.awt.Color(0, 15, 40)));
        KB_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KB_Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        KB_Label.setIconTextGap(20);
        KB_Label.setOpaque(true);
        KB_Label.setRequestFocusEnabled(false);
        KB_Label.setVerifyInputWhenFocusTarget(false);
        KB_Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Main_panel.add(KB_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 280));

        S5.setBackground(new java.awt.Color(51, 51, 51));
        Main_panel.add(S5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2370, 1050, 10));

        TypeLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        TypeLabel1.setForeground(new java.awt.Color(102, 102, 102));
        TypeLabel1.setText("Non-Veg. Pizzas");
        Main_panel.add(TypeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2320, -1, -1));

        jScrollPane1.setViewportView(Main_panel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1350, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setLocationRelativeTo(null);
        try{
    Class.forName("java.sql.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
    Statement stat = con.createStatement();
    String query = "Select * from Location;";
    rs = stat.executeQuery(query);
    while(rs.next()){
        String pn = rs.getString("Plot_no");
        String ar = rs.getString("Area");
        String land = rs.getString("Landmark");
        String pin = rs.getString("Pincode");
        String ct = rs.getString("City");
        String resi = rs.getString("Residence");
        Address.setText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
        Address.setToolTipText(pn + ", " + land + ", " + resi + ", " + ar + ", " + ct + ", Gujarat" + " - " + pin);
                
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, "Error in Adress",null,-2);
}
        
C1.setVisible(false);
C2.setVisible(false);
C3.setVisible(false);
C4.setVisible(false);
C5.setVisible(false);
C6.setVisible(false);
C11.setVisible(false);
C12.setVisible(false);
C13.setVisible(false);
C14.setVisible(false);
C15.setVisible(false);
C16.setVisible(false);
C17.setVisible(false);
C18.setVisible(false);
C19.setVisible(false);
C20.setVisible(false);
C21.setVisible(false);
C22.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add3ActionPerformed
C3.setVisible(true);
Add3.setVisible(false);
C3.setValue(1);// TODO add your handling code here:
    }//GEN-LAST:event_Add3ActionPerformed

    private void Add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add6ActionPerformed
C6.setVisible(true);
Add6.setVisible(false);
C6.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add6ActionPerformed

    private void Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add5ActionPerformed
C5.setVisible(true);
Add5.setVisible(false);
C5.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add5ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
C2.setVisible(true);
Add2.setVisible(false);
C2.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
C1.setVisible(true);
Add1.setVisible(false);
C1.setValue(1);
// TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed

    private void Add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add4ActionPerformed
C4.setVisible(true);
Add4.setVisible(false);
C4.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add4ActionPerformed

    private void Add11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add11ActionPerformed
C11.setVisible(true);
Add11.setVisible(false);
C11.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add11ActionPerformed

    private void Add12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add12ActionPerformed
C12.setVisible(true);
Add12.setVisible(false);
C12.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add12ActionPerformed

    private void Add13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add13ActionPerformed
C13.setVisible(true);
Add13.setVisible(false);
C13.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add13ActionPerformed

    private void Add14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add14ActionPerformed
C14.setVisible(true);
Add14.setVisible(false);
C14.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add14ActionPerformed

    private void Add15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add15ActionPerformed
C15.setVisible(true);
Add15.setVisible(false);
C15.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add15ActionPerformed

    private void Add16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add16ActionPerformed
C16.setVisible(true);
Add16.setVisible(false);
C16.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add16ActionPerformed

    private void Add17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add17ActionPerformed
C17.setVisible(true);
Add17.setVisible(false);
C17.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add17ActionPerformed

    private void RestaurantLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = blue>Go back to Restaurants(Surat) Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            Project_Frames._4_Main_Order_Gujarat_Surat.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseClicked

    private void RestaurantLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseEntered
        RestaurantLabel.setText("<html><u>Restaurant(Surat)</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseEntered

    private void RestaurantLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantLabelMouseExited
        RestaurantLabel.setText("Restaurant(Surat) /");
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantLabelMouseExited

    private void LocationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = Green>Go back to Location Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _3_Location.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseClicked

    private void LocationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseEntered
        LocationLabel.setText("<html><u>Location</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseEntered

    private void LocationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationLabelMouseExited
        LocationLabel.setText("Location /");
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationLabelMouseExited

    private void SigninLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseClicked
        int Ans = JOptionPane.showConfirmDialog(this, "<html><font size = 15 face = rockwell color = orange>Go back to Sign in Page ?", null, 1,-1);
        if(Ans == JOptionPane.YES_OPTION){
            _2_Login.main(null);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseClicked

    private void SigninLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseEntered
        SigninLabel.setText("<html><u>Sign in</u> /</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseEntered

    private void SigninLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninLabelMouseExited
        SigninLabel.setText("Sign in /");
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninLabelMouseExited

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
int c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23;
        c1 = (int) C1.getValue();
        c2 = (int) C2.getValue();
        c3 = (int) C3.getValue();
        c4 = (int) C4.getValue();
        c5 = (int) C5.getValue();
        c6 = (int) C6.getValue();
        c11 = (int) C11.getValue();
        c12 = (int) C12.getValue();
        c13 = (int) C13.getValue();
        c14 = (int) C14.getValue();
        c15 = (int) C15.getValue();
        c16 = (int) C16.getValue();
        c17 = (int) C17.getValue();
        c18 = (int) C18.getValue();
        c19 = (int) C19.getValue();
        c20 = (int) C20.getValue();
        c21 = (int) C21.getValue();
        c22 = (int) C22.getValue();
        
        if(c1 > 0 || c2 > 0 || c3 > 0 || c4 > 0 || c5 > 0 || c6 > 0 || c11 > 0 || c12 > 0 || c13 > 0 || c14 > 0 || c15 > 0 || c16 > 0 || c17 > 0 || c18 > 0 || c19 > 0 || c20 > 0 || c21 > 0 || c22 > 0 ){
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/vatsalproject", "root", "mysql");
            stat = con.createStatement();
            String query1 = "Delete from cart;";
            stat.executeUpdate(query1);

            if (c1 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Margherita', 150," + c1 + ");";
                stat.executeUpdate(query);
            }   
            if (c2 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Fresh Veggie', 180," + c2 + ");";
                stat.executeUpdate(query);
            }   
            if (c3 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Digital Veggie Paradise', 200," + c3 + ");";
                stat.executeUpdate(query);
            }   
            if (c4 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Paneer Makhni', 210," + c4 + ");";
                stat.executeUpdate(query);
            }   
            if (c5 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Deluxe Veggie', 230," + c5 + ");";
                stat.executeUpdate(query);
            }   
            if (c6 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Peppy Paneer', 250," + c6 + ");";
                stat.executeUpdate(query);
            }   
            if (c11 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Farmhouse', 260," + c11 + ");";
                stat.executeUpdate(query);
            }   
            if (c12 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Mexicaan Green Wave', 280," + c12 + ");";
                stat.executeUpdate(query);
            }   
            if (c13 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Pepper Barbeque', 120," + c13 + ");";
                stat.executeUpdate(query);
            }   
            if (c14 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Chicken Golden Delight', 150," + c14 + ");";
                stat.executeUpdate(query);
            }   
            if (c15 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Dominator', 180," + c15 + ");";
                stat.executeUpdate(query);
            }   
            if (c16 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Chunky Chicken', 210," + c16 + ");";
                stat.executeUpdate(query);
            }   
            if (c17 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Non-Veg. Supreme', 230," + c17 + ");";
                stat.executeUpdate(query);
            }   
            if (c18 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'CocaCola Zero', 80," + c18 + ");";
                stat.executeUpdate(query);
            }   
            if (c19 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Coke', 80," + c19 + ");";
                stat.executeUpdate(query);
            }   
            if (c20 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Fanta', 80," + c20 + ");";
                stat.executeUpdate(query);
            }   
            if (c21 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Sprite', 80," + c21 + ");";
                stat.executeUpdate(query);
            }   
            if (c22 > 0) {
                String query = "Insert into cart values ('Laziz Pizza', 'Thumsup', 80," + c22 + ");";
                stat.executeUpdate(query);
            }   

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error in Cart Button", null, 2);
        }

int Ans = JOptionPane.showConfirmDialog(this, "<html><font color = green size = 15 face = rockwell>Do you want to add Items to Cart?", null, 0, -1);
if (Ans == JOptionPane.YES_OPTION) {
            Restaurants.Cart.main(null);
            this.dispose();
    }
    }
else
    JOptionPane.showMessageDialog(this, "<html><font color = red size = 15 face = rockwell>Select any Item", null, -1);
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBtnActionPerformed

    private void Add18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add18ActionPerformed
C18.setVisible(true);
Add18.setVisible(false);
C18.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add18ActionPerformed

    private void Add19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add19ActionPerformed
C19.setVisible(true);
Add19.setVisible(false);
C19.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add19ActionPerformed

    private void Add20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add20ActionPerformed
C20.setVisible(true);
Add20.setVisible(false);
C20.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add20ActionPerformed

    private void Add21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add21ActionPerformed
C21.setVisible(true);
Add21.setVisible(false);
C21.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add21ActionPerformed

    private void Add22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add22ActionPerformed
C22.setVisible(true);
Add22.setVisible(false);
C22.setValue(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Surat_Krish_Bhog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Surat_Laziz_Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add11;
    private javax.swing.JButton Add12;
    private javax.swing.JButton Add13;
    private javax.swing.JButton Add14;
    private javax.swing.JButton Add15;
    private javax.swing.JButton Add16;
    private javax.swing.JButton Add17;
    private javax.swing.JButton Add18;
    private javax.swing.JButton Add19;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Add20;
    private javax.swing.JButton Add21;
    private javax.swing.JButton Add22;
    private javax.swing.JButton Add3;
    private javax.swing.JButton Add4;
    private javax.swing.JButton Add5;
    private javax.swing.JButton Add6;
    private javax.swing.JLabel Address;
    private javax.swing.JSpinner C1;
    private javax.swing.JSpinner C11;
    private javax.swing.JSpinner C12;
    private javax.swing.JSpinner C13;
    private javax.swing.JSpinner C14;
    private javax.swing.JSpinner C15;
    private javax.swing.JSpinner C16;
    private javax.swing.JSpinner C17;
    private javax.swing.JSpinner C18;
    private javax.swing.JSpinner C19;
    private javax.swing.JSpinner C2;
    private javax.swing.JSpinner C20;
    private javax.swing.JSpinner C21;
    private javax.swing.JSpinner C22;
    private javax.swing.JSpinner C3;
    private javax.swing.JSpinner C4;
    private javax.swing.JSpinner C5;
    private javax.swing.JSpinner C6;
    private javax.swing.JButton CartBtn;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I11;
    private javax.swing.JLabel I12;
    private javax.swing.JLabel I13;
    private javax.swing.JLabel I14;
    private javax.swing.JLabel I15;
    private javax.swing.JLabel I16;
    private javax.swing.JLabel I17;
    private javax.swing.JLabel I18;
    private javax.swing.JLabel I19;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I20;
    private javax.swing.JLabel I21;
    private javax.swing.JLabel I22;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JLabel I5;
    private javax.swing.JLabel I6;
    private javax.swing.JSeparator IS1;
    private javax.swing.JSeparator IS12;
    private javax.swing.JSeparator IS13;
    private javax.swing.JSeparator IS14;
    private javax.swing.JSeparator IS15;
    private javax.swing.JSeparator IS16;
    private javax.swing.JSeparator IS18;
    private javax.swing.JSeparator IS19;
    private javax.swing.JSeparator IS2;
    private javax.swing.JSeparator IS20;
    private javax.swing.JSeparator IS21;
    private javax.swing.JSeparator IS22;
    private javax.swing.JSeparator IS3;
    private javax.swing.JSeparator IS4;
    private javax.swing.JSeparator IS5;
    private javax.swing.JSeparator IS6;
    private javax.swing.JLabel KB_Label;
    private javax.swing.JLabel LabelBack;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JLabel PALabel;
    private javax.swing.JLabel RestaurantLabel;
    private javax.swing.JSeparator S1;
    private javax.swing.JSeparator S2;
    private javax.swing.JSeparator S3;
    private javax.swing.JSeparator S4;
    private javax.swing.JSeparator S5;
    private javax.swing.JPanel SDPanel;
    private javax.swing.JScrollPane SDScroll;
    private javax.swing.JLabel SigninLabel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel TypeLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
